// All 214 Kangxi radicals with simplified forms, examples, and category.
// `tier`: 'basic' (40 most fundamental) | 'common' (next ~60, top 100) | 'extended' (rest of 214)
export const allRadicals = [
  // 1-10
  { kangxi: 1,  char: "一", form: null, pinyin: "yī",   meaning: "One",                 cat: "strokes", ex: [{char:"三",pinyin:"sān",meaning:"three"},{char:"天",pinyin:"tiān",meaning:"heaven"}], colloquial: "横", tier: "basic", comment: "The single horizontal stroke 横. Foundation of writing — appears in numbers and many compounds." },
  { kangxi: 2,  char: "丨", form: null, pinyin: "gǔn",  meaning: "Vertical line",       cat: "strokes", ex: [{char:"中",pinyin:"zhōng",meaning:"middle"},{char:"串",pinyin:"chuàn",meaning:"string"}], colloquial: "竖", tier: "extended", comment: "A bare vertical line 竖. Pure structural stroke; rarely a phonetic, common as a center axis." },
  { kangxi: 3,  char: "丶", form: null, pinyin: "zhǔ",  meaning: "Dot",                 cat: "strokes", ex: [{char:"主",pinyin:"zhǔ",meaning:"master"},{char:"丹",pinyin:"dān",meaning:"red"}], colloquial: "点", tier: "extended", comment: "The dot 点. Tiny but everywhere — opens many characters at the top." },
  { kangxi: 4,  char: "丿", form: null, pinyin: "piě",  meaning: "Slash, downstroke",   cat: "strokes", ex: [{char:"久",pinyin:"jiǔ",meaning:"long-time"},{char:"乎",pinyin:"hū",meaning:"in/of"}], colloquial: "撇", tier: "extended", comment: "Left-falling stroke 撇. Adds motion; pairs with 捺 to make 人." },
  { kangxi: 5,  char: "乙", form: "乚", pinyin: "yǐ",   meaning: "Second, twist",       cat: "strokes", ex: [{char:"九",pinyin:"jiǔ",meaning:"nine"},{char:"乱",pinyin:"luàn",meaning:"chaos"}], colloquial: "乙字旁", tier: "extended", comment: "A twist or hook. Origin of 'second' in the Heavenly Stems; visible in 九, 也." },
  { kangxi: 6,  char: "亅", form: null, pinyin: "jué",  meaning: "Hook",                cat: "strokes", ex: [{char:"了",pinyin:"le",meaning:"completed"},{char:"事",pinyin:"shì",meaning:"matter"}], colloquial: "钩", tier: "extended", comment: "Just a hook 钩. Final-stroke shape rather than a meaning radical." },
  { kangxi: 7,  char: "二", form: null, pinyin: "èr",   meaning: "Two",                 cat: "strokes", ex: [{char:"五",pinyin:"wǔ",meaning:"five"},{char:"井",pinyin:"jǐng",meaning:"well"}], colloquial: "二字旁", tier: "common", comment: "Two horizontal lines = 'two'. Often an upper/lower frame: 元, 云." },
  { kangxi: 8,  char: "亠", form: null, pinyin: "tóu",  meaning: "Lid",                 cat: "tools", ex: [{char:"京",pinyin:"jīng",meaning:"capital"},{char:"亮",pinyin:"liàng",meaning:"bright"}], colloquial: "亠头", tier: "extended", comment: "The 'lid' on top. Almost always sits as a roof: 京, 高, 亮." },
  { kangxi: 9,  char: "人", form: "亻", pinyin: "rén",  meaning: "Person",              cat: "people",    ex: [{char:"今",pinyin:"jīn",meaning:"today"},{char:"你",pinyin:"nǐ",meaning:"you"}], colloquial: "单人旁, 人字头", tier: "basic", comment: "Person standing. Side form 亻 means 'human-related': 你 他 们 仁." },
  { kangxi: 10, char: "儿", form: null, pinyin: "ér",   meaning: "Child, legs",         cat: "people",    ex: [{char:"元",pinyin:"yuán",meaning:"origin"},{char:"充",pinyin:"chōng",meaning:"fill"}], colloquial: "儿座底", tier: "common", comment: "A pair of legs underneath. Sits at the bottom of standing figures: 元 兄 先." },

  // 11-20
  { kangxi: 11, char: "入", form: null, pinyin: "rù",   meaning: "Enter",               cat: "actions", ex: [{char:"内",pinyin:"nèi",meaning:"inside"},{char:"全",pinyin:"quán",meaning:"whole"}], colloquial: "入字头", tier: "extended", comment: "To enter — looks like 人 inverted. Mostly archaic; survives in 内, 全." },
  { kangxi: 12, char: "八", form: null, pinyin: "bā",   meaning: "Eight",               cat: "strokes", ex: [{char:"公",pinyin:"gōng",meaning:"public"},{char:"分",pinyin:"fēn",meaning:"divide"}], colloquial: "八字旁", tier: "basic", comment: "Eight = to divide. Two strokes pulling apart: 分, 公, 半." },
  { kangxi: 13, char: "冂", form: null, pinyin: "jiōng",meaning: "Down box",            cat: "tools", ex: [{char:"内",pinyin:"nèi",meaning:"inside"},{char:"册",pinyin:"cè",meaning:"booklet"}], colloquial: "同字框", tier: "extended", comment: "Open downward box 冂 — think 'wide hat'. Encloses things: 内, 同." },
  { kangxi: 14, char: "冖", form: null, pinyin: "mì",   meaning: "Cover",               cat: "tools", ex: [{char:"军",pinyin:"jūn",meaning:"army"},{char:"农",pinyin:"nóng",meaning:"farmer"}], colloquial: "秃宝盖", tier: "extended", comment: "The 'bald cover' 秃宝盖. A roof without a dot: 写, 军, 农." },
  { kangxi: 15, char: "冫", form: null, pinyin: "bīng", meaning: "Ice",                 cat: "nature",  ex: [{char:"冬",pinyin:"dōng",meaning:"winter"},{char:"冷",pinyin:"lěng",meaning:"cold"}], colloquial: "两点水", tier: "common", comment: "Two-dot water = ice 冫. Cold/frozen things: 冬, 冷, 冰." },
  { kangxi: 16, char: "几", form: null, pinyin: "jī",   meaning: "Small table",         cat: "tools", ex: [{char:"凡",pinyin:"fán",meaning:"ordinary"},{char:"凭",pinyin:"píng",meaning:"rely"}], colloquial: "几字旁", tier: "common", comment: "A small low table. Loaned for 'how many': 几, 凡." },
  { kangxi: 17, char: "凵", form: null, pinyin: "qiǎn", meaning: "Open box",            cat: "tools", ex: [{char:"凶",pinyin:"xiōng",meaning:"fierce"},{char:"出",pinyin:"chū",meaning:"out"}], colloquial: "凵字底", tier: "extended", comment: "Open-top box 凵. Container shape: 出 'come out of the box'." },
  { kangxi: 18, char: "刀", form: "刂", pinyin: "dāo",  meaning: "Knife, sword",        cat: "tools", ex: [{char:"分",pinyin:"fēn",meaning:"divide"},{char:"初",pinyin:"chū",meaning:"first"}], colloquial: "立刀旁", tier: "basic", comment: "Knife. Right-side form 刂 means 'cut/blade': 切, 刚, 利." },
  { kangxi: 19, char: "力", form: null, pinyin: "lì",   meaning: "Power, force",        cat: "actions", ex: [{char:"加",pinyin:"jiā",meaning:"add"},{char:"助",pinyin:"zhù",meaning:"help"}], colloquial: "力字旁", tier: "basic", comment: "A bent arm flexing — strength. Effortful actions: 加, 努, 助." },
  { kangxi: 20, char: "勹", form: null, pinyin: "bāo",  meaning: "Wrap",                cat: "actions", ex: [{char:"勺",pinyin:"sháo",meaning:"spoon"},{char:"包",pinyin:"bāo",meaning:"wrap"}], colloquial: "包字头", tier: "extended", comment: "To wrap — like an arm curling around. 包, 勺, 勿." },

  // 21-30
  { kangxi: 21, char: "匕", form: null, pinyin: "bǐ",   meaning: "Spoon, ladle",        cat: "tools", ex: [{char:"北",pinyin:"běi",meaning:"north"},{char:"化",pinyin:"huà",meaning:"change"}], colloquial: "匕字旁", tier: "common", comment: "A spoon or ladle. Also a person bent over: 北 (two backs), 化." },
  { kangxi: 22, char: "匚", form: null, pinyin: "fāng", meaning: "Box, container",      cat: "tools", ex: [{char:"区",pinyin:"qū",meaning:"area"},{char:"匠",pinyin:"jiàng",meaning:"craftsman"}], colloquial: "三框", tier: "extended", comment: "Box opening to the right 匚. Containers: 区, 匠, 匣." },
  { kangxi: 23, char: "匸", form: null, pinyin: "xì",   meaning: "Hidden enclosure",    cat: "tools", ex: [{char:"匹",pinyin:"pǐ",meaning:"measure"},{char:"医",pinyin:"yī",meaning:"doctor"}], colloquial: "匸字框", tier: "extended", comment: "Hidden enclosure 匸. Conceals: 医, 匹." },
  { kangxi: 24, char: "十", form: null, pinyin: "shí",  meaning: "Ten",                 cat: "strokes", ex: [{char:"什",pinyin:"shén",meaning:"what"},{char:"叶",pinyin:"yè",meaning:"leaf"}], colloquial: "十字旁", tier: "basic", comment: "Ten 十 — a cross. Completeness; building block in dates and counts." },
  { kangxi: 25, char: "卜", form: null, pinyin: "bǔ",   meaning: "Divination",          cat: "actions", ex: [{char:"占",pinyin:"zhàn",meaning:"occupy"},{char:"卡",pinyin:"kǎ",meaning:"card"}], colloquial: "卜字旁", tier: "extended", comment: "Divination crack on a turtle shell 卜. Predict, ask: 占, 卦." },
  { kangxi: 26, char: "卩", form: "㔾", pinyin: "jié",  meaning: "Seal",                cat: "tools", ex: [{char:"印",pinyin:"yìn",meaning:"print"},{char:"危",pinyin:"wēi",meaning:"danger"}], colloquial: "单耳刀", tier: "common", comment: "A kneeling seal/stamp 卩. 'Single-ear' on the right: 印, 即, 卷." },
  { kangxi: 27, char: "厂", form: null, pinyin: "chǎng",meaning: "Cliff, factory",      cat: "nature", ex: [{char:"厅",pinyin:"tīng",meaning:"hall"},{char:"原",pinyin:"yuán",meaning:"origin"}], colloquial: "厂字头", tier: "common", comment: "A cliff face 厂. Things under an overhang: 厅, 历, 厚." },
  { kangxi: 28, char: "厶", form: null, pinyin: "sī",   meaning: "Private, cocoon",     cat: "actions", ex: [{char:"去",pinyin:"qù",meaning:"go"},{char:"参",pinyin:"cān",meaning:"join"}], colloquial: "私字旁", tier: "extended", comment: "A private/cocoon shape 厶. 'Self/private': 私, 去, 公." },
  { kangxi: 29, char: "又", form: null, pinyin: "yòu",  meaning: "Right hand, again",   cat: "actions", ex: [{char:"反",pinyin:"fǎn",meaning:"opposite"},{char:"取",pinyin:"qǔ",meaning:"take"}], colloquial: "又字旁", tier: "basic", comment: "A right hand 又 — 'and/again'. Repetition or holding: 友, 反, 取." },
  { kangxi: 30, char: "口", form: null, pinyin: "kǒu",  meaning: "Mouth, opening",      cat: "actions",    ex: [{char:"古",pinyin:"gǔ",meaning:"ancient"},{char:"可",pinyin:"kě",meaning:"can/may"}], colloquial: "口字旁", tier: "basic", comment: "Mouth — a square. Anything spoken, eaten, or named: 吃, 叫, 唱." },

  // 31-40
  { kangxi: 31, char: "囗", form: null, pinyin: "wéi",  meaning: "Enclosure",           cat: "tools", ex: [{char:"国",pinyin:"guó",meaning:"country"},{char:"园",pinyin:"yuán",meaning:"garden"}], colloquial: "国字框", tier: "common", comment: "Big enclosure 囗 — borders/walls: 国, 园, 困, 围." },
  { kangxi: 32, char: "土", form: null, pinyin: "tǔ",   meaning: "Earth, soil",         cat: "nature",  ex: [{char:"在",pinyin:"zài",meaning:"at/be"},{char:"地",pinyin:"dì",meaning:"earth/place"}], colloquial: "提土旁", tier: "basic", comment: "Earth/soil. As 土 on the left → things of earth: 地, 城, 块." },
  { kangxi: 33, char: "士", form: null, pinyin: "shì",  meaning: "Scholar, soldier",    cat: "people",    ex: [{char:"声",pinyin:"shēng",meaning:"sound"},{char:"壮",pinyin:"zhuàng",meaning:"strong"}], colloquial: "士字旁", tier: "common", comment: "A scholar/warrior — 一 over 十. Status, gentlemen: 壮, 声." },
  { kangxi: 34, char: "夂", form: null, pinyin: "zhǐ",  meaning: "Go, follow",          cat: "actions", ex: [{char:"冬",pinyin:"dōng",meaning:"winter"},{char:"处",pinyin:"chǔ",meaning:"place"}], colloquial: "折文旁", tier: "extended", comment: "To go/follow — a foot trailing. Mostly seen in 冬, 处." },
  { kangxi: 35, char: "夊", form: null, pinyin: "suī",  meaning: "Walk slowly",         cat: "actions", ex: [{char:"夏",pinyin:"xià",meaning:"summer"},{char:"夔",pinyin:"kuí",meaning:"a-monster"}], colloquial: "夊字旁", tier: "extended", comment: "Walk slowly, drag-foot. Survives in 夏, 夔." },
  { kangxi: 36, char: "夕", form: null, pinyin: "xī",   meaning: "Evening, dusk",       cat: "nature",  ex: [{char:"外",pinyin:"wài",meaning:"outside"},{char:"多",pinyin:"duō",meaning:"many"}], colloquial: "夕字旁", tier: "common", comment: "Evening, half-moon 夕. Twilight things: 多 (many evenings), 外, 名." },
  { kangxi: 37, char: "大", form: null, pinyin: "dà",   meaning: "Big, great",          cat: "people", ex: [{char:"天",pinyin:"tiān",meaning:"sky"},{char:"太",pinyin:"tài",meaning:"too"}], colloquial: "大字头", tier: "basic", comment: "A person stretching arms wide = 'big'. Size, greatness: 太, 天, 奇." },
  { kangxi: 38, char: "女", form: null, pinyin: "nǚ",   meaning: "Woman, female",       cat: "people",    ex: [{char:"好",pinyin:"hǎo",meaning:"good"},{char:"妈",pinyin:"mā",meaning:"mom"}], colloquial: "女字旁", tier: "basic", comment: "A kneeling woman. On the left → female roles: 妈, 姐, 好, 娃." },
  { kangxi: 39, char: "子", form: null, pinyin: "zǐ",   meaning: "Child, son",          cat: "people",    ex: [{char:"孩",pinyin:"hái",meaning:"child"},{char:"学",pinyin:"xué",meaning:"study"}], colloquial: "子字旁", tier: "basic", comment: "A swaddled child 子. Offspring, study: 孩, 孙, 学, 字." },
  { kangxi: 40, char: "宀", form: null, pinyin: "mián", meaning: "Roof",                cat: "tools", ex: [{char:"守",pinyin:"shǒu",meaning:"guard"},{char:"家",pinyin:"jiā",meaning:"home"}], colloquial: "宝盖头", tier: "basic", comment: "Roof 宀 — 'house dome'. Domestic things: 家, 安, 宿, 守." },

  // 41-50
  { kangxi: 41, char: "寸", form: null, pinyin: "cùn",  meaning: "Inch, thumb",         cat: "actions", ex: [{char:"寺",pinyin:"sì",meaning:"temple"},{char:"对",pinyin:"duì",meaning:"correct"}], colloquial: "寸字旁", tier: "common", comment: "An inch / thumb-width — small measure of action: 寸, 对, 寺, 封." },
  { kangxi: 42, char: "小", form: null, pinyin: "xiǎo", meaning: "Small, little",       cat: "actions", ex: [{char:"少",pinyin:"shǎo",meaning:"few"},{char:"尖",pinyin:"jiān",meaning:"point"}], colloquial: "小字头", tier: "basic", comment: "Three little dots = small 小. Diminutives: 少, 尖, 尘." },
  { kangxi: 43, char: "尢", form: null, pinyin: "wāng", meaning: "Lame",                cat: "people",    ex: [{char:"尤",pinyin:"yóu",meaning:"especially"},{char:"就",pinyin:"jiù",meaning:"then"}], colloquial: "尢字旁", tier: "extended", comment: "A lame/crooked person 尢. Rare: 尤, 就." },
  { kangxi: 44, char: "尸", form: null, pinyin: "shī",  meaning: "Corpse, body",        cat: "people",    ex: [{char:"尺",pinyin:"chǐ",meaning:"ruler"},{char:"屋",pinyin:"wū",meaning:"house"}], colloquial: "尸字头", tier: "common", comment: "Body/corpse 尸 — bent figure. Buildings & body: 屋, 居, 屁, 尾." },
  { kangxi: 45, char: "屮", form: null, pinyin: "chè",  meaning: "Sprout",              cat: "plants",  ex: [{char:"屯",pinyin:"tún",meaning:"village"},{char:"芔",pinyin:"huì",meaning:"grass"}], colloquial: "屮字旁", tier: "extended", comment: "A young sprout 屮. Lives on inside other plant radicals." },
  { kangxi: 46, char: "山", form: null, pinyin: "shān", meaning: "Mountain",            cat: "nature",  ex: [{char:"岩",pinyin:"yán",meaning:"rock"},{char:"岛",pinyin:"dǎo",meaning:"island"}], colloquial: "山字旁", tier: "basic", comment: "Three peaks = mountain 山. Terrain features: 岩, 岛, 峰, 岸." },
  { kangxi: 47, char: "巛", form: "川", pinyin: "chuān",meaning: "River, stream",       cat: "nature",  ex: [{char:"州",pinyin:"zhōu",meaning:"state"},{char:"巡",pinyin:"xún",meaning:"patrol"}], colloquial: "三拐", tier: "common", comment: "Flowing river lines 巛/川. Water on the move: 州, 巡." },
  { kangxi: 48, char: "工", form: null, pinyin: "gōng", meaning: "Work, labor",         cat: "actions", ex: [{char:"左",pinyin:"zuǒ",meaning:"left"},{char:"功",pinyin:"gōng",meaning:"merit"}], colloquial: "工字旁", tier: "common", comment: "Carpenter's square / work 工. Tasks and craft: 左, 功, 巧." },
  { kangxi: 49, char: "己", form: null, pinyin: "jǐ",   meaning: "Oneself",             cat: "people",    ex: [{char:"已",pinyin:"yǐ",meaning:"already"},{char:"巴",pinyin:"bā",meaning:"hope"}], colloquial: "己字旁", tier: "common", comment: "Self 己 — a coiled body. 已, 巴, also Heavenly Stem." },
  { kangxi: 50, char: "巾", form: null, pinyin: "jīn",  meaning: "Turban, scarf",       cat: "tools", ex: [{char:"市",pinyin:"shì",meaning:"market"},{char:"布",pinyin:"bù",meaning:"cloth"}], colloquial: "巾字旁", tier: "common", comment: "A piece of cloth hanging 巾. Fabrics: 布, 帽, 帜, 帝." },

  // 51-60
  { kangxi: 51, char: "干", form: null, pinyin: "gān",  meaning: "Dry, shield",         cat: "actions", ex: [{char:"平",pinyin:"píng",meaning:"flat"},{char:"年",pinyin:"nián",meaning:"year"}], colloquial: "干字旁", tier: "common", comment: "A shield / dry. Either meaning: 平, 年, 幸." },
  { kangxi: 52, char: "幺", form: null, pinyin: "yāo",  meaning: "Small, tiny",         cat: "actions", ex: [{char:"幻",pinyin:"huàn",meaning:"illusion"},{char:"幼",pinyin:"yòu",meaning:"young"}], colloquial: "幺字旁", tier: "extended", comment: "Tiny — a single thread 幺. Smallness, beginnings: 幻, 幼." },
  { kangxi: 53, char: "广", form: null, pinyin: "guǎng",meaning: "House on cliff",      cat: "tools", ex: [{char:"店",pinyin:"diàn",meaning:"shop"},{char:"座",pinyin:"zuò",meaning:"seat"}], colloquial: "广字旁", tier: "common", comment: "A house on a cliff 广. Roofed structures: 店, 床, 库, 庙." },
  { kangxi: 54, char: "廴", form: null, pinyin: "yǐn",  meaning: "Long stride",         cat: "actions", ex: [{char:"延",pinyin:"yán",meaning:"extend"},{char:"建",pinyin:"jiàn",meaning:"build"}], colloquial: "建字底", tier: "extended", comment: "Long-stride walk 廴. Extended motion: 延, 建, 廷." },
  { kangxi: 55, char: "廾", form: null, pinyin: "gǒng", meaning: "Two hands, twenty",   cat: "people",    ex: [{char:"开",pinyin:"kāi",meaning:"open"},{char:"弄",pinyin:"nòng",meaning:"play"}], colloquial: "弄字底", tier: "extended", comment: "Two hands raised 廾. Reverent action: 开, 弄, 弊." },
  { kangxi: 56, char: "弋", form: null, pinyin: "yì",   meaning: "Shoot, dart",         cat: "actions", ex: [{char:"式",pinyin:"shì",meaning:"style"},{char:"武",pinyin:"wǔ",meaning:"martial"}], colloquial: "弋字旁", tier: "extended", comment: "A short dart/javelin 弋. Survives in 式, 武." },
  { kangxi: 57, char: "弓", form: null, pinyin: "gōng", meaning: "Bow",                 cat: "tools", ex: [{char:"引",pinyin:"yǐn",meaning:"draw"},{char:"张",pinyin:"zhāng",meaning:"open"}], colloquial: "弓字旁", tier: "common", comment: "A bow 弓 — drawn weapon. Archery & tension: 引, 张, 强, 弱." },
  { kangxi: 58, char: "彐", form: "彑", pinyin: "jì",   meaning: "Pig snout",           cat: "nature",  ex: [{char:"归",pinyin:"guī",meaning:"return"},{char:"当",pinyin:"dāng",meaning:"serve"}], colloquial: "雪字底", tier: "extended", comment: "Pig's snout 彐 — bristly hand. Now mostly the top of 雪, 当, 归." },
  { kangxi: 59, char: "彡", form: null, pinyin: "shān", meaning: "Hair, decoration",    cat: "tools", ex: [{char:"形",pinyin:"xíng",meaning:"form"},{char:"影",pinyin:"yǐng",meaning:"shadow"}], colloquial: "三撇", tier: "common", comment: "Three diagonal hairs 彡. Surface texture: 形, 影, 彩, 彭." },
  { kangxi: 60, char: "彳", form: null, pinyin: "chì",  meaning: "Small step",          cat: "actions", ex: [{char:"彼",pinyin:"bǐ",meaning:"that"},{char:"德",pinyin:"dé",meaning:"virtue"}], colloquial: "双人旁", tier: "common", comment: "Step with the left foot 彳 — 'double-person'. Movement: 行, 往, 很, 得." },

  // 61-70
  { kangxi: 61, char: "心", form: "忄⺗", pinyin: "xīn", meaning: "Heart, mind",        cat: "people",    ex: [{char:"必",pinyin:"bì",meaning:"must"},{char:"忙",pinyin:"máng",meaning:"busy"}], colloquial: "竖心旁, 心字底", tier: "basic", comment: "Heart 心. Side form 忄 = feelings: 想, 忙, 怕, 情, 爱." },
  { kangxi: 62, char: "戈", form: null, pinyin: "gē",   meaning: "Halberd, dagger-axe", cat: "tools", ex: [{char:"成",pinyin:"chéng",meaning:"become"},{char:"我",pinyin:"wǒ",meaning:"I"}], colloquial: "戈字旁", tier: "common", comment: "A halberd / dagger-axe 戈. Weapons & 'I': 我, 战, 成, 或." },
  { kangxi: 63, char: "户", form: "戶", pinyin: "hù",   meaning: "Door, household",     cat: "tools", ex: [{char:"房",pinyin:"fáng",meaning:"room"},{char:"扁",pinyin:"biǎn",meaning:"flat"}], colloquial: "户字头", tier: "common", comment: "A single-leaf door 户. Households: 房, 所, 扁." },
  { kangxi: 64, char: "手", form: "扌", pinyin: "shǒu", meaning: "Hand",                cat: "people",    ex: [{char:"持",pinyin:"chí",meaning:"hold"},{char:"打",pinyin:"dǎ",meaning:"hit"}], colloquial: "提手旁", tier: "basic", comment: "Hand 手. Side form 扌 = manual actions: 打, 拿, 推, 找." },
  { kangxi: 65, char: "支", form: null, pinyin: "zhī",  meaning: "Branch, support",     cat: "actions", ex: [{char:"支",pinyin:"zhī",meaning:"support"},{char:"鼓",pinyin:"gǔ",meaning:"drum"}], colloquial: "支字旁", tier: "extended", comment: "A hand holding a branch 支. Branching/support: 支, 翅." },
  { kangxi: 66, char: "攴", form: "攵", pinyin: "pū",   meaning: "Knock, tap",          cat: "actions", ex: [{char:"收",pinyin:"shōu",meaning:"collect"},{char:"政",pinyin:"zhèng",meaning:"politics"}], colloquial: "反文旁", tier: "common", comment: "A hand with stick = tap/strike 攴. Right form 攵: 收, 教, 政." },
  { kangxi: 67, char: "文", form: null, pinyin: "wén",  meaning: "Script, literature",  cat: "tools", ex: [{char:"斋",pinyin:"zhāi",meaning:"studio"},{char:"斑",pinyin:"bān",meaning:"spot"}], colloquial: "文字旁", tier: "common", comment: "Crossed lines = pattern/script 文. Writing: 斋, 斑." },
  { kangxi: 68, char: "斗", form: null, pinyin: "dǒu",  meaning: "Measure, dipper",     cat: "tools", ex: [{char:"料",pinyin:"liào",meaning:"material"},{char:"斜",pinyin:"xié",meaning:"slanted"}], colloquial: "斗字旁", tier: "common", comment: "Long-handled dipper 斗. Measure: 料, 斜, 斟." },
  { kangxi: 69, char: "斤", form: null, pinyin: "jīn",  meaning: "Axe, catty",          cat: "tools", ex: [{char:"新",pinyin:"xīn",meaning:"new"},{char:"断",pinyin:"duàn",meaning:"break"}], colloquial: "斤字旁", tier: "common", comment: "An axe 斤. Cutting & weighing: 新, 断, 斧." },
  { kangxi: 70, char: "方", form: null, pinyin: "fāng", meaning: "Square, raft",        cat: "tools", ex: [{char:"放",pinyin:"fàng",meaning:"release"},{char:"旅",pinyin:"lǚ",meaning:"travel"}], colloquial: "方字旁", tier: "common", comment: "A square / direction 方. Places & methods: 放, 旅, 旁, 旗." },

  // 71-80
  { kangxi: 71, char: "无", form: "旡", pinyin: "wú",   meaning: "Not, without",        cat: "actions", ex: [{char:"既",pinyin:"jì",meaning:"already"},{char:"暨",pinyin:"jì",meaning:"and"}], colloquial: "无字旁", tier: "extended", comment: "Negation 'without' 无. Stuck inside 既, 暨." },
  { kangxi: 72, char: "日", form: null, pinyin: "rì",   meaning: "Sun, day",            cat: "nature",  ex: [{char:"白",pinyin:"bái",meaning:"white"},{char:"明",pinyin:"míng",meaning:"bright"}], colloquial: "日字旁", tier: "basic", comment: "The sun 日 — round, with a stroke inside. Time & light: 明, 时, 春, 早." },
  { kangxi: 73, char: "曰", form: null, pinyin: "yuē",  meaning: "Say, speak",          cat: "actions", ex: [{char:"曲",pinyin:"qū",meaning:"bend"},{char:"更",pinyin:"gèng",meaning:"more"}], colloquial: "曰字旁", tier: "common", comment: "Speak/say 曰 — wider than 日. Sayings: 曲, 更, 书." },
  { kangxi: 74, char: "月", form: null, pinyin: "yuè",  meaning: "Moon, month",         cat: "nature",  ex: [{char:"有",pinyin:"yǒu",meaning:"have"},{char:"服",pinyin:"fú",meaning:"clothes"}], colloquial: "月字旁", tier: "basic", comment: "The moon 月 (also 'flesh' merged). Months & body parts: 朋, 期, 肝, 脸." },
  { kangxi: 75, char: "木", form: null, pinyin: "mù",   meaning: "Wood, tree",          cat: "plants",  ex: [{char:"板",pinyin:"bǎn",meaning:"board"},{char:"根",pinyin:"gēn",meaning:"root"}], colloquial: "木字旁", tier: "basic", comment: "A tree 木 with roots and branches. Wood things: 林, 树, 板, 校." },
  { kangxi: 76, char: "欠", form: null, pinyin: "qiàn", meaning: "Lack, yawn",          cat: "actions", ex: [{char:"欢",pinyin:"huān",meaning:"happy"},{char:"次",pinyin:"cì",meaning:"next"}], colloquial: "欠字旁", tier: "common", comment: "Open mouth yawning = 'lack' 欠. Wanting/breath: 欢, 次, 歌." },
  { kangxi: 77, char: "止", form: null, pinyin: "zhǐ",  meaning: "Stop, foot",          cat: "actions", ex: [{char:"正",pinyin:"zhèng",meaning:"upright"},{char:"步",pinyin:"bù",meaning:"step"}], colloquial: "止字旁", tier: "common", comment: "A foot stopped 止. Halt/walk: 正, 步, 此, 武." },
  { kangxi: 78, char: "歹", form: null, pinyin: "dǎi",  meaning: "Bad, death",          cat: "actions", ex: [{char:"死",pinyin:"sǐ",meaning:"die"},{char:"残",pinyin:"cán",meaning:"cruel"}], colloquial: "歹字旁", tier: "common", comment: "Bone fragments — death 歹. Negative outcomes: 死, 残, 殊." },
  { kangxi: 79, char: "殳", form: null, pinyin: "shū",  meaning: "Weapon, lance",       cat: "tools", ex: [{char:"段",pinyin:"duàn",meaning:"section"},{char:"殷",pinyin:"yīn",meaning:"abundant"}], colloquial: "殳字旁", tier: "extended", comment: "A pole-weapon 殳 in hand. Found in 段, 殷, 般." },
  { kangxi: 80, char: "毋", form: null, pinyin: "wú",   meaning: "Do not",              cat: "people", ex: [{char:"母",pinyin:"mǔ",meaning:"mother"},{char:"每",pinyin:"měi",meaning:"every"}], colloquial: "毋字旁", tier: "common", comment: "'Don't' 毋 — woman with bar. Warning: 母, 每, 毓 (closely related forms)." },

  // 81-90
  { kangxi: 81, char: "比", form: null, pinyin: "bǐ",   meaning: "Compare",             cat: "actions", ex: [{char:"毕",pinyin:"bì",meaning:"finish"},{char:"皆",pinyin:"jiē",meaning:"all"}], colloquial: "比字旁", tier: "common", comment: "Two people side by side = compare 比. 毕, 皆, 昆." },
  { kangxi: 82, char: "毛", form: null, pinyin: "máo",  meaning: "Fur, hair",           cat: "people", ex: [{char:"毫",pinyin:"háo",meaning:"hair"},{char:"毯",pinyin:"tǎn",meaning:"blanket"}], colloquial: "毛字旁", tier: "common", comment: "Tufts of fur 毛. Hair, fluff: 毫, 毯, 毡." },
  { kangxi: 83, char: "氏", form: null, pinyin: "shì",  meaning: "Clan, family",        cat: "people",    ex: [{char:"民",pinyin:"mín",meaning:"people"},{char:"昏",pinyin:"hūn",meaning:"dusk"}], colloquial: "氏字旁", tier: "extended", comment: "Clan/family name 氏. Lineage: 民, 昏, 纸 (different origin)." },
  { kangxi: 84, char: "气", form: null, pinyin: "qì",   meaning: "Air, breath",         cat: "nature",  ex: [{char:"氛",pinyin:"fēn",meaning:"atmosphere"},{char:"氧",pinyin:"yǎng",meaning:"oxygen"}], colloquial: "气字头", tier: "common", comment: "Rising vapor 气 — three wavy lines. Gases: 氛, 氧, 氢." },
  { kangxi: 85, char: "水", form: "氵", pinyin: "shuǐ", meaning: "Water",               cat: "nature",  ex: [{char:"永",pinyin:"yǒng",meaning:"forever"},{char:"洋",pinyin:"yáng",meaning:"ocean"}], colloquial: "三点水", tier: "basic", comment: "Water 水. Side form 氵 (three drops): 河, 海, 流, 洗." },
  { kangxi: 86, char: "火", form: "灬", pinyin: "huǒ",  meaning: "Fire",                cat: "nature",  ex: [{char:"灯",pinyin:"dēng",meaning:"lamp"},{char:"烧",pinyin:"shāo",meaning:"burn"}], colloquial: "四点底", tier: "basic", comment: "Fire 火 — flames. Bottom form 灬 (four dots): 灯, 烧, 热, 照." },
  { kangxi: 87, char: "爪", form: "爫", pinyin: "zhǎo", meaning: "Claw, talon",         cat: "people",    ex: [{char:"爬",pinyin:"pá",meaning:"climb"},{char:"爱",pinyin:"ài",meaning:"love"}], colloquial: "爪字头", tier: "common", comment: "A claw reaching down 爪. Top form 爫: 爬, 爱, 受, 爵." },
  { kangxi: 88, char: "父", form: null, pinyin: "fù",   meaning: "Father",              cat: "people",    ex: [{char:"爸",pinyin:"bà",meaning:"dad"},{char:"爷",pinyin:"yé",meaning:"grandpa"}], colloquial: "父字头", tier: "common", comment: "Father 父 — hand holding axe. 爸, 爷." },
  { kangxi: 89, char: "爻", form: null, pinyin: "yáo",  meaning: "Lines (of trigram)",  cat: "tools", ex: [{char:"爽",pinyin:"shuǎng",meaning:"refreshing"},{char:"爾",pinyin:"ěr",meaning:"thou"}], colloquial: "爻字旁", tier: "extended", comment: "Crossed lines of divination trigrams 爻. Rare: 爽, 爾." },
  { kangxi: 90, char: "爿", form: "丬", pinyin: "qiáng",meaning: "Split wood (left)",   cat: "tools", ex: [{char:"床",pinyin:"chuáng",meaning:"bed"},{char:"将",pinyin:"jiāng",meaning:"will"}], colloquial: "爿字旁", tier: "extended", comment: "Left half of a split tree 爿. Beds & sides: 床 (with cliff), 将, 状." },

  // 91-100
  { kangxi: 91, char: "片", form: null, pinyin: "piàn", meaning: "Slice, piece",        cat: "tools", ex: [{char:"版",pinyin:"bǎn",meaning:"edition"},{char:"牌",pinyin:"pái",meaning:"plate"}], colloquial: "片字旁", tier: "common", comment: "Right half of split wood 片. Slices & cards: 版, 牌, 牒." },
  { kangxi: 92, char: "牙", form: null, pinyin: "yá",   meaning: "Tooth, fang",         cat: "people",    ex: [{char:"邪",pinyin:"xié",meaning:"evil"},{char:"雅",pinyin:"yǎ",meaning:"elegant"}], colloquial: "牙字旁", tier: "common", comment: "A fang 牙. Teeth-related: 邪, 雅, 穿." },
  { kangxi: 93, char: "牛", form: "牜", pinyin: "niú",  meaning: "Cow, ox",             cat: "animals",  ex: [{char:"牧",pinyin:"mù",meaning:"shepherd"},{char:"物",pinyin:"wù",meaning:"thing"}], colloquial: "牛字旁", tier: "common", comment: "An ox/cow 牛. Livestock: 牧, 物, 特, 牢." },
  { kangxi: 94, char: "犬", form: "犭", pinyin: "quǎn", meaning: "Dog",                 cat: "animals",  ex: [{char:"犯",pinyin:"fàn",meaning:"commit"},{char:"狗",pinyin:"gǒu",meaning:"dog"}], colloquial: "反犬旁", tier: "basic", comment: "Dog 犬. Side form 犭 = animals: 狗, 猫, 狮, 猪." },
  { kangxi: 95, char: "玄", form: null, pinyin: "xuán", meaning: "Dark, mysterious",    cat: "actions", ex: [{char:"率",pinyin:"lǜ",meaning:"rate"},{char:"兹",pinyin:"zī",meaning:"this"}], colloquial: "玄字旁", tier: "extended", comment: "Mysterious / dark 玄. Abstract: 率, 兹." },
  { kangxi: 96, char: "玉", form: "王", pinyin: "yù",   meaning: "Jade",                cat: "tools", ex: [{char:"玩",pinyin:"wán",meaning:"play"},{char:"理",pinyin:"lǐ",meaning:"reason"}], colloquial: "王字旁", tier: "common", comment: "Jade 玉 — three discs strung. Side form 王 (no dot): 玩, 理, 珠, 球." },
  { kangxi: 97, char: "瓜", form: null, pinyin: "guā",  meaning: "Melon, gourd",        cat: "plants",  ex: [{char:"瓢",pinyin:"piáo",meaning:"ladle"},{char:"瓣",pinyin:"bàn",meaning:"petal"}], colloquial: "瓜字旁", tier: "common", comment: "A melon on a vine 瓜. Gourds: 瓢, 瓣." },
  { kangxi: 98, char: "瓦", form: null, pinyin: "wǎ",   meaning: "Tile",                cat: "tools", ex: [{char:"瓶",pinyin:"píng",meaning:"bottle"},{char:"瓷",pinyin:"cí",meaning:"porcelain"}], colloquial: "瓦字旁", tier: "common", comment: "Roof tile 瓦. Pottery: 瓶, 瓷, 甑." },
  { kangxi: 99, char: "甘", form: null, pinyin: "gān",  meaning: "Sweet",               cat: "actions", ex: [{char:"甜",pinyin:"tián",meaning:"sweet"},{char:"甚",pinyin:"shèn",meaning:"very"}], colloquial: "甘字旁", tier: "common", comment: "Sweet 甘 — mouth holding sweetness. 甜, 甚." },
  { kangxi: 100,char: "生", form: null, pinyin: "shēng",meaning: "Birth, life, raw",    cat: "actions",  ex: [{char:"产",pinyin:"chǎn",meaning:"produce"},{char:"甥",pinyin:"shēng",meaning:"nephew"}], colloquial: "生字旁", tier: "common", comment: "A sprout breaking earth = life 生. Birth & rawness: 产, 甥, 性 (via 心)." },

  // 101-110
  { kangxi: 101,char: "用", form: null, pinyin: "yòng", meaning: "Use",                 cat: "actions", ex: [{char:"甩",pinyin:"shuǎi",meaning:"swing"},{char:"甫",pinyin:"fǔ",meaning:"just"}], colloquial: "用字旁", tier: "extended", comment: "To use 用. Often a phonetic: 甩, 甫, 庸." },
  { kangxi: 102,char: "田", form: null, pinyin: "tián", meaning: "Field",               cat: "nature",  ex: [{char:"思",pinyin:"sī",meaning:"think"},{char:"留",pinyin:"liú",meaning:"stay"}], colloquial: "田字旁", tier: "basic", comment: "A field 田 — cross-shaped paddy. Farming: 思, 男, 留, 番." },
  { kangxi: 103,char: "疋", form: "⺪", pinyin: "pǐ",   meaning: "Roll of cloth",       cat: "tools", ex: [{char:"疏",pinyin:"shū",meaning:"sparse"},{char:"疑",pinyin:"yí",meaning:"doubt"}], colloquial: "疋字旁", tier: "extended", comment: "A bolt of cloth 疋. Survives in 疏, 疑." },
  { kangxi: 104,char: "疒", form: null, pinyin: "nè",   meaning: "Sickness",            cat: "people",    ex: [{char:"病",pinyin:"bìng",meaning:"illness"},{char:"疼",pinyin:"téng",meaning:"ache"}], colloquial: "病字旁", tier: "common", comment: "Sickness leaning on a bed 疒. Illness: 病, 疼, 症, 痛." },
  { kangxi: 105,char: "癶", form: null, pinyin: "bō",   meaning: "Two feet apart",      cat: "actions", ex: [{char:"登",pinyin:"dēng",meaning:"climb"},{char:"发",pinyin:"fā",meaning:"emit"}], colloquial: "登字头", tier: "extended", comment: "Two feet apart 癶 — climbing stance. 登, 发." },
  { kangxi: 106,char: "白", form: null, pinyin: "bái",  meaning: "White",               cat: "tools", ex: [{char:"百",pinyin:"bǎi",meaning:"hundred"},{char:"的",pinyin:"de",meaning:"of"}], colloquial: "白字旁", tier: "common", comment: "White 白 — sun with a ray. Brightness/clarity: 百, 的, 皇." },
  { kangxi: 107,char: "皮", form: null, pinyin: "pí",   meaning: "Skin, leather",       cat: "people",    ex: [{char:"皱",pinyin:"zhòu",meaning:"wrinkle"},{char:"皴",pinyin:"cūn",meaning:"chapped"}], colloquial: "皮字旁", tier: "common", comment: "Skin/peel 皮. Surface: 皱, 颇, 波 (phonetic)." },
  { kangxi: 108,char: "皿", form: null, pinyin: "mǐn",  meaning: "Dish, vessel",        cat: "tools", ex: [{char:"盆",pinyin:"pén",meaning:"basin"},{char:"盘",pinyin:"pán",meaning:"plate"}], colloquial: "皿字底", tier: "common", comment: "A dish/vessel 皿. Containers below: 盆, 盘, 盒, 盖." },
  { kangxi: 109,char: "目", form: "罒", pinyin: "mù",   meaning: "Eye",                 cat: "people",    ex: [{char:"眼",pinyin:"yǎn",meaning:"eye"},{char:"看",pinyin:"kàn",meaning:"look"}], colloquial: "目字旁", tier: "basic", comment: "Eye 目 — vertical 'sun'. Vision: 看, 眼, 睡, 瞧." },
  { kangxi: 110,char: "矛", form: null, pinyin: "máo",  meaning: "Spear, lance",        cat: "tools", ex: [{char:"矜",pinyin:"jīn",meaning:"pity"},{char:"矟",pinyin:"shuò",meaning:"spear"}], colloquial: "矛字旁", tier: "extended", comment: "A lance/spear 矛. Pointed weapons: 矜, 矟, 柔." },

  // 111-120
  { kangxi: 111,char: "矢", form: null, pinyin: "shǐ",  meaning: "Arrow",               cat: "tools", ex: [{char:"知",pinyin:"zhī",meaning:"know"},{char:"短",pinyin:"duǎn",meaning:"short"}], colloquial: "矢字旁", tier: "common", comment: "An arrow 矢. Aim/measure: 知, 短, 矩." },
  { kangxi: 112,char: "石", form: null, pinyin: "shí",  meaning: "Stone, rock",         cat: "nature",  ex: [{char:"砂",pinyin:"shā",meaning:"sand"},{char:"碎",pinyin:"suì",meaning:"break"}], colloquial: "石字旁", tier: "common", comment: "Stone 石 — cliff with a chunk. Rocks: 砂, 碎, 硬, 砖." },
  { kangxi: 113,char: "示", form: "礻", pinyin: "shì",  meaning: "Spirit, altar",       cat: "actions", ex: [{char:"礼",pinyin:"lǐ",meaning:"ritual"},{char:"祝",pinyin:"zhù",meaning:"wish"}], colloquial: "示字旁", tier: "common", comment: "Altar/spirit 示. Side form 礻 = ritual: 礼, 神, 祝, 福." },
  { kangxi: 114,char: "禸", form: null, pinyin: "róu",  meaning: "Track, footprint",    cat: "actions", ex: [{char:"禹",pinyin:"yǔ",meaning:"Yu(emperor)"},{char:"离",pinyin:"lí",meaning:"leave"}], colloquial: "禸字旁", tier: "extended", comment: "Beast track 禸. Survives in 禹, 离." },
  { kangxi: 115,char: "禾", form: null, pinyin: "hé",   meaning: "Grain, cereal",       cat: "plants",  ex: [{char:"利",pinyin:"lì",meaning:"benefit"},{char:"和",pinyin:"hé",meaning:"and/peace"}], colloquial: "禾木旁", tier: "common", comment: "Stalk of grain 禾. Cereals: 利, 和, 秋, 种." },
  { kangxi: 116,char: "穴", form: null, pinyin: "xué",  meaning: "Cave",                cat: "tools", ex: [{char:"空",pinyin:"kōng",meaning:"empty"},{char:"窗",pinyin:"chuāng",meaning:"window"}], colloquial: "穴宝盖", tier: "common", comment: "A cave dwelling 穴. Hollows: 空, 窗, 究, 穿." },
  { kangxi: 117,char: "立", form: null, pinyin: "lì",   meaning: "Stand",               cat: "actions", ex: [{char:"站",pinyin:"zhàn",meaning:"stand"},{char:"端",pinyin:"duān",meaning:"end"}], colloquial: "立字旁", tier: "common", comment: "Person standing on the ground = stand 立. 站, 端, 章." },
  { kangxi: 118,char: "竹", form: "⺮", pinyin: "zhú",  meaning: "Bamboo",              cat: "plants",  ex: [{char:"笑",pinyin:"xiào",meaning:"laugh"},{char:"第",pinyin:"dì",meaning:"ordinal"}], colloquial: "竹字头", tier: "basic", comment: "Bamboo 竹. Top form ⺮ = bamboo objects: 笑, 笔, 答, 算." },
  { kangxi: 119,char: "米", form: null, pinyin: "mǐ",   meaning: "Rice",                cat: "tools", ex: [{char:"类",pinyin:"lèi",meaning:"category"},{char:"粉",pinyin:"fěn",meaning:"powder"}], colloquial: "米字旁", tier: "basic", comment: "Grains of rice 米. Foods of grain: 类, 粉, 粒, 糖." },
  { kangxi: 120,char: "糸", form: "纟", pinyin: "mì",   meaning: "Silk, thread",        cat: "tools", ex: [{char:"纪",pinyin:"jì",meaning:"record"},{char:"绩",pinyin:"jì",meaning:"achievement"}], colloquial: "绞丝旁", tier: "basic", comment: "Twisted silk threads 糸. Side form 纟 = thread: 纸, 红, 给, 经." },

  // 121-130
  { kangxi: 121,char: "缶", form: null, pinyin: "fǒu",  meaning: "Earthen jar",         cat: "tools", ex: [{char:"缸",pinyin:"gāng",meaning:"vat"},{char:"罐",pinyin:"guàn",meaning:"pot"}], colloquial: "缶字旁", tier: "common", comment: "Earthenware jar 缶. Pottery: 缸, 罐." },
  { kangxi: 122,char: "网", form: "罒", pinyin: "wǎng", meaning: "Net",                 cat: "tools", ex: [{char:"罗",pinyin:"luó",meaning:"net"},{char:"罪",pinyin:"zuì",meaning:"crime"}], colloquial: "罗字头", tier: "common", comment: "A net 网 — top form 罒. Catching: 罗, 罪, 罢, 置." },
  { kangxi: 123,char: "羊", form: "⺶", pinyin: "yáng", meaning: "Sheep, goat",         cat: "animals",  ex: [{char:"美",pinyin:"měi",meaning:"beautiful"},{char:"群",pinyin:"qún",meaning:"group"}], colloquial: "羊字旁", tier: "common", comment: "Sheep 羊 — head with horns. Goodness: 美, 群, 鲜." },
  { kangxi: 124,char: "羽", form: null, pinyin: "yǔ",   meaning: "Feather, plume",      cat: "animals", ex: [{char:"翅",pinyin:"chì",meaning:"wing"},{char:"翻",pinyin:"fān",meaning:"turn"}], colloquial: "羽字旁", tier: "common", comment: "Feathers 羽 — two wings. Flight: 翅, 翻, 翼, 翔." },
  { kangxi: 125,char: "老", form: "耂", pinyin: "lǎo",  meaning: "Old",                 cat: "people",    ex: [{char:"考",pinyin:"kǎo",meaning:"test"},{char:"者",pinyin:"zhě",meaning:"one-who"}], colloquial: "老字头", tier: "common", comment: "An old man with cane 老. Top form 耂: 考, 者, 孝." },
  { kangxi: 126,char: "而", form: null, pinyin: "ér",   meaning: "And, beard",          cat: "actions", ex: [{char:"耐",pinyin:"nài",meaning:"endure"},{char:"耍",pinyin:"shuǎ",meaning:"play"}], colloquial: "而字旁", tier: "common", comment: "A beard 而 — also 'and/yet'. Conjunctive: 耐, 耍." },
  { kangxi: 127,char: "耒", form: null, pinyin: "lěi",  meaning: "Plow",                cat: "tools", ex: [{char:"耕",pinyin:"gēng",meaning:"till"},{char:"耗",pinyin:"hào",meaning:"consume"}], colloquial: "耒字旁", tier: "extended", comment: "A plow 耒. Farming tools: 耕, 耗, 耘." },
  { kangxi: 128,char: "耳", form: null, pinyin: "ěr",   meaning: "Ear",                 cat: "people",    ex: [{char:"取",pinyin:"qǔ",meaning:"take"},{char:"职",pinyin:"zhí",meaning:"duty"}], colloquial: "耳字旁", tier: "common", comment: "Ear 耳. Hearing & officials: 取, 闻, 职, 聪." },
  { kangxi: 129,char: "聿", form: "⺺", pinyin: "yù",   meaning: "Brush, writing",      cat: "tools", ex: [{char:"肃",pinyin:"sù",meaning:"solemn"},{char:"肆",pinyin:"sì",meaning:"four"}], colloquial: "聿字旁", tier: "extended", comment: "A hand holding a brush 聿. Writing: 肃, 肆, 肇." },
  { kangxi: 130,char: "肉", form: "⺼", pinyin: "ròu",  meaning: "Meat, flesh",         cat: "people",    ex: [{char:"胃",pinyin:"wèi",meaning:"stomach"},{char:"脸",pinyin:"liǎn",meaning:"face"}], colloquial: "肉字旁", tier: "common", comment: "Flesh 肉. Often written like 月 on the side = body parts: 胃, 脸, 脑, 胖." },

  // 131-140
  { kangxi: 131,char: "臣", form: null, pinyin: "chén", meaning: "Minister, official",  cat: "people",    ex: [{char:"卧",pinyin:"wò",meaning:"lie"},{char:"臧",pinyin:"zāng",meaning:"good"}], colloquial: "臣字旁", tier: "common", comment: "A staring eye = minister 臣. Officials: 卧, 临, 监." },
  { kangxi: 132,char: "自", form: null, pinyin: "zì",   meaning: "Self, nose",          cat: "people",    ex: [{char:"臭",pinyin:"chòu",meaning:"smelly"},{char:"臬",pinyin:"niè",meaning:"target"}], colloquial: "自字旁", tier: "common", comment: "Self/nose 自. Origin of 'I': 臭, 息." },
  { kangxi: 133,char: "至", form: null, pinyin: "zhì",  meaning: "Arrive, until",       cat: "actions", ex: [{char:"致",pinyin:"zhì",meaning:"send"},{char:"臻",pinyin:"zhēn",meaning:"reach"}], colloquial: "至字旁", tier: "common", comment: "Arrow reaching the ground = arrive 至. 到, 致, 屋." },
  { kangxi: 134,char: "臼", form: null, pinyin: "jiù",  meaning: "Mortar",              cat: "tools", ex: [{char:"舅",pinyin:"jiù",meaning:"uncle"},{char:"舆",pinyin:"yú",meaning:"carriage"}], colloquial: "臼字旁", tier: "extended", comment: "A mortar 臼. Grinding & old: 舅, 舆, 旧." },
  { kangxi: 135,char: "舌", form: null, pinyin: "shé",  meaning: "Tongue",              cat: "people",    ex: [{char:"舍",pinyin:"shě",meaning:"cottage"},{char:"舔",pinyin:"tiǎn",meaning:"lick"}], colloquial: "舌字旁", tier: "common", comment: "Tongue 舌 sticking out. Speaking & tasting: 舍, 舔, 甜 (sweet on tongue)." },
  { kangxi: 136,char: "舛", form: null, pinyin: "chuǎn",meaning: "Oppose, mismatch",    cat: "actions", ex: [{char:"舜",pinyin:"shùn",meaning:"Shun"},{char:"舞",pinyin:"wǔ",meaning:"dance"}], colloquial: "舛字旁", tier: "extended", comment: "Two feet pointing apart = oppose 舛. 舜, 舞." },
  { kangxi: 137,char: "舟", form: null, pinyin: "zhōu", meaning: "Boat",                cat: "tools", ex: [{char:"船",pinyin:"chuán",meaning:"ship"},{char:"航",pinyin:"háng",meaning:"navigate"}], colloquial: "舟字旁", tier: "common", comment: "A boat 舟. Watercraft: 船, 航, 般, 艇." },
  { kangxi: 138,char: "艮", form: null, pinyin: "gěn",  meaning: "Stop, blunt",         cat: "actions", ex: [{char:"良",pinyin:"liáng",meaning:"good"},{char:"艰",pinyin:"jiān",meaning:"hard"}], colloquial: "艮字旁", tier: "common", comment: "A back-turned eye = stop 艮. 良, 艰, 跟 (foot+艮)." },
  { kangxi: 139,char: "色", form: null, pinyin: "sè",   meaning: "Color",               cat: "tools", ex: [{char:"艳",pinyin:"yàn",meaning:"gorgeous"},{char:"艴",pinyin:"fú",meaning:"angry"}], colloquial: "色字旁", tier: "common", comment: "Color 色 — knife over kneeling person. 艳, 艴." },
  { kangxi: 140,char: "艸", form: "艹", pinyin: "cǎo",  meaning: "Grass",               cat: "plants",  ex: [{char:"花",pinyin:"huā",meaning:"flower"},{char:"茶",pinyin:"chá",meaning:"tea"}], colloquial: "草字头", tier: "basic", comment: "Two sprouts 艸. Top form 艹 = plants: 花, 草, 茶, 菜." },

  // 141-150
  { kangxi: 141,char: "虍", form: null, pinyin: "hū",   meaning: "Tiger pattern",       cat: "animals",  ex: [{char:"虎",pinyin:"hǔ",meaning:"tiger"},{char:"虐",pinyin:"nüè",meaning:"abuse"}], colloquial: "虎字头", tier: "common", comment: "Tiger's stripes 虍. Big cats: 虎, 虐, 虚." },
  { kangxi: 142,char: "虫", form: null, pinyin: "chóng",meaning: "Insect",              cat: "animals",  ex: [{char:"强",pinyin:"qiáng",meaning:"strong"},{char:"蛇",pinyin:"shé",meaning:"snake"}], colloquial: "虫字旁", tier: "basic", comment: "A small worm/snake 虫. Insects & reptiles: 蛇, 蚊, 蚂, 强." },
  { kangxi: 143,char: "血", form: null, pinyin: "xuè",  meaning: "Blood",               cat: "people",    ex: [{char:"衅",pinyin:"xìn",meaning:"quarrel"},{char:"衄",pinyin:"nǜ",meaning:"nosebleed"}], colloquial: "血字旁", tier: "common", comment: "Drop of blood in dish 血. 衅, 衄." },
  { kangxi: 144,char: "行", form: null, pinyin: "xíng", meaning: "Walk, go",            cat: "actions", ex: [{char:"街",pinyin:"jiē",meaning:"street"},{char:"衡",pinyin:"héng",meaning:"balance"}], colloquial: "双人旁", tier: "common", comment: "A crossroads 行 = walk/go. Travel & rows: 街, 衡, 衍." },
  { kangxi: 145,char: "衣", form: "衤", pinyin: "yī",   meaning: "Clothing",            cat: "tools", ex: [{char:"初",pinyin:"chū",meaning:"first"},{char:"被",pinyin:"bèi",meaning:"quilt"}], colloquial: "衣字旁", tier: "basic", comment: "Clothing 衣 with collar & sleeves. Side form 衤: 初, 被, 裙, 袖." },
  { kangxi: 146,char: "襾", form: "覀", pinyin: "yà",   meaning: "Cover, west",         cat: "tools", ex: [{char:"西",pinyin:"xī",meaning:"west"},{char:"要",pinyin:"yào",meaning:"want"}], colloquial: "西字头", tier: "common", comment: "A cap/cover 襾 (top 覀). Survives in 西, 要, 票." },
  { kangxi: 147,char: "见", form: "見", pinyin: "jiàn", meaning: "See",                 cat: "actions", ex: [{char:"观",pinyin:"guān",meaning:"observe"},{char:"觉",pinyin:"jué",meaning:"feel"}], colloquial: "见字旁", tier: "common", comment: "To see 见 — eye on legs. Perception: 观, 觉, 视, 览." },
  { kangxi: 148,char: "角", form: null, pinyin: "jiǎo", meaning: "Horn, angle",         cat: "animals", ex: [{char:"解",pinyin:"jiě",meaning:"untie"},{char:"触",pinyin:"chù",meaning:"touch"}], colloquial: "角字旁", tier: "common", comment: "A horn 角. Angles & solving: 解, 触." },
  { kangxi: 149,char: "言", form: "讠", pinyin: "yán",  meaning: "Speech, words",       cat: "actions", ex: [{char:"说",pinyin:"shuō",meaning:"speak"},{char:"讲",pinyin:"jiǎng",meaning:"say"}], colloquial: "言字旁", tier: "basic", comment: "Words coming from mouth 言. Side form 讠 = speech: 说, 话, 请, 谢." },
  { kangxi: 150,char: "谷", form: null, pinyin: "gǔ",   meaning: "Valley",              cat: "nature",  ex: [{char:"豁",pinyin:"huō",meaning:"open"},{char:"豂",pinyin:"liáo",meaning:"deep-valley"}], colloquial: "谷字旁", tier: "common", comment: "A valley 谷 with stream emerging. Geography & abstract: 豁, 欲 (with 欠)." },

  // 151-160
  { kangxi: 151,char: "豆", form: null, pinyin: "dòu",  meaning: "Bean, vessel",        cat: "tools", ex: [{char:"豌",pinyin:"wān",meaning:"pea"},{char:"豉",pinyin:"chǐ",meaning:"fermented-bean"}], colloquial: "豆字旁", tier: "common", comment: "A ritual stem-cup 豆 = bean. Legumes & vessels: 豌, 豉, 豆腐." },
  { kangxi: 152,char: "豕", form: null, pinyin: "shǐ",  meaning: "Pig",                 cat: "animals",  ex: [{char:"象",pinyin:"xiàng",meaning:"elephant"},{char:"豪",pinyin:"háo",meaning:"grand"}], colloquial: "豕字旁", tier: "common", comment: "A pig 豕. Livestock: 象, 豪, 家 (pig under roof)." },
  { kangxi: 153,char: "豸", form: null, pinyin: "zhì",  meaning: "Badger, cat",         cat: "animals",  ex: [{char:"豹",pinyin:"bào",meaning:"leopard"},{char:"貌",pinyin:"mào",meaning:"appearance"}], colloquial: "豸字旁", tier: "common", comment: "A cat-like crouching beast 豸. Predators: 豹, 貌, 貂." },
  { kangxi: 154,char: "贝", form: "貝", pinyin: "bèi",  meaning: "Shell, money",        cat: "tools", ex: [{char:"财",pinyin:"cái",meaning:"wealth"},{char:"贷",pinyin:"dài",meaning:"loan"}], colloquial: "贝字旁", tier: "basic", comment: "A cowrie shell 贝 = money. Trade: 财, 货, 贵, 购." },
  { kangxi: 155,char: "赤", form: null, pinyin: "chì",  meaning: "Red, bare",           cat: "tools", ex: [{char:"赦",pinyin:"shè",meaning:"pardon"},{char:"赫",pinyin:"hè",meaning:"awe"}], colloquial: "赤字旁", tier: "common", comment: "Red 赤 — fire glow. 赦, 赫." },
  { kangxi: 156,char: "走", form: null, pinyin: "zǒu",  meaning: "Walk, run",           cat: "actions", ex: [{char:"起",pinyin:"qǐ",meaning:"rise"},{char:"超",pinyin:"chāo",meaning:"surpass"}], colloquial: "走字旁", tier: "basic", comment: "A person striding 走 = walk/run. Going: 起, 超, 越, 趣." },
  { kangxi: 157,char: "足", form: "⻊", pinyin: "zú",   meaning: "Foot",                cat: "people",    ex: [{char:"跑",pinyin:"pǎo",meaning:"run"},{char:"路",pinyin:"lù",meaning:"road"}], colloquial: "足字旁", tier: "basic", comment: "Foot 足. Side form ⻊ = leg actions: 跑, 跳, 路, 踢." },
  { kangxi: 158,char: "身", form: null, pinyin: "shēn", meaning: "Body, self",          cat: "people",    ex: [{char:"躺",pinyin:"tǎng",meaning:"lie"},{char:"躲",pinyin:"duǒ",meaning:"hide"}], colloquial: "身字旁", tier: "common", comment: "A pregnant body 身 = self. Personal: 躺, 躲, 射." },
  { kangxi: 159,char: "车", form: "車", pinyin: "chē",  meaning: "Cart, vehicle",       cat: "tools", ex: [{char:"轮",pinyin:"lún",meaning:"wheel"},{char:"军",pinyin:"jūn",meaning:"army"}], colloquial: "车字旁", tier: "basic", comment: "A cart 车 (top-down view). Vehicles: 轮, 软, 转, 较." },
  { kangxi: 160,char: "辛", form: null, pinyin: "xīn",  meaning: "Bitter, hardship",    cat: "actions", ex: [{char:"辜",pinyin:"gū",meaning:"crime"},{char:"辣",pinyin:"là",meaning:"spicy"}], colloquial: "辛字旁", tier: "common", comment: "Bitter herb on stem 辛 — hardship. Punishment: 辜, 辣, 辨." },

  // 161-170
  { kangxi: 161,char: "辰", form: null, pinyin: "chén", meaning: "Morning, dragon",     cat: "nature",  ex: [{char:"农",pinyin:"nóng",meaning:"farm"},{char:"辱",pinyin:"rǔ",meaning:"shame"}], colloquial: "辰字旁", tier: "common", comment: "Morning constellation 辰. Time: 农, 辱, 晨." },
  { kangxi: 162,char: "辵", form: "辶", pinyin: "chuò", meaning: "Walk, stride",        cat: "actions", ex: [{char:"迎",pinyin:"yíng",meaning:"welcome"},{char:"道",pinyin:"dào",meaning:"way"}], colloquial: "走之旁", tier: "basic", comment: "Walk-and-stop 辵 — bottom form 辶 = movement: 道, 进, 还, 远." },
  { kangxi: 163,char: "邑", form: "阝", pinyin: "yì",   meaning: "City (right)",        cat: "tools", ex: [{char:"都",pinyin:"dōu",meaning:"all/capital"},{char:"邮",pinyin:"yóu",meaning:"post"}], colloquial: "右耳旁", tier: "common", comment: "City — right form 阝. On the RIGHT = town/place: 都, 邮, 那, 邦." },
  { kangxi: 164,char: "酉", form: null, pinyin: "yǒu",  meaning: "Wine vessel",         cat: "tools", ex: [{char:"酒",pinyin:"jiǔ",meaning:"wine"},{char:"醒",pinyin:"xǐng",meaning:"wake"}], colloquial: "酉字旁", tier: "common", comment: "Wine jar 酉. Fermented things: 酒, 醒, 醋, 酸." },
  { kangxi: 165,char: "釆", form: null, pinyin: "biàn", meaning: "Distinguish",         cat: "actions", ex: [{char:"释",pinyin:"shì",meaning:"release"},{char:"采",pinyin:"cǎi",meaning:"pick"}], colloquial: "釆字旁", tier: "extended", comment: "To distinguish — paw with claws 釆. 释, 采." },
  { kangxi: 166,char: "里", form: null, pinyin: "lǐ",   meaning: "Village, mile",       cat: "tools", ex: [{char:"重",pinyin:"zhòng",meaning:"heavy"},{char:"野",pinyin:"yě",meaning:"wild"}], colloquial: "里字旁", tier: "common", comment: "Village/mile 里 (field over earth). Distance: 重, 野, 量." },
  { kangxi: 167,char: "金", form: "钅", pinyin: "jīn",  meaning: "Gold, metal",         cat: "tools", ex: [{char:"银",pinyin:"yín",meaning:"silver"},{char:"铁",pinyin:"tiě",meaning:"iron"}], colloquial: "金字旁", tier: "basic", comment: "Gold/metal 金. Side form 钅 = metals: 银, 铁, 铜, 钱." },
  { kangxi: 168,char: "长", form: "長", pinyin: "cháng",meaning: "Long, grow",          cat: "actions", ex: [{char:"套",pinyin:"tào",meaning:"cover"},{char:"肆",pinyin:"sì",meaning:"unbridled"}], colloquial: "长字旁", tier: "common", comment: "Long hair flowing 长. Length & growth: 套, 张 (different)." },
  { kangxi: 169,char: "门", form: "門", pinyin: "mén",  meaning: "Gate, door",          cat: "tools", ex: [{char:"间",pinyin:"jiān",meaning:"between"},{char:"问",pinyin:"wèn",meaning:"ask"}], colloquial: "门字框", tier: "basic", comment: "Double-leaf gate 门. Gateways: 间, 问, 闻, 闪." },
  { kangxi: 170,char: "阜", form: "阝", pinyin: "fù",   meaning: "Mound (left)",        cat: "nature",  ex: [{char:"阳",pinyin:"yáng",meaning:"sun"},{char:"阴",pinyin:"yīn",meaning:"shade"}], colloquial: "左耳旁", tier: "common", comment: "Mound — left form 阝. On the LEFT = hill/terrain: 阳, 阴, 队, 防." },

  // 171-180
  { kangxi: 171,char: "隶", form: null, pinyin: "lì",   meaning: "Slave, subject",      cat: "actions", ex: [{char:"隸",pinyin:"lì",meaning:"slave"},{char:"逮",pinyin:"dài",meaning:"catch"}], colloquial: "隶字旁", tier: "extended", comment: "To capture/subdue 隶. Rare: 隸, 逮." },
  { kangxi: 172,char: "隹", form: null, pinyin: "zhuī", meaning: "Short-tailed bird",   cat: "animals",  ex: [{char:"集",pinyin:"jí",meaning:"gather"},{char:"雇",pinyin:"gù",meaning:"hire"}], colloquial: "隹字旁", tier: "common", comment: "Short-tailed bird 隹. Birds: 集, 雇, 雏, 雌." },
  { kangxi: 173,char: "雨", form: null, pinyin: "yǔ",   meaning: "Rain",                cat: "nature",  ex: [{char:"雪",pinyin:"xuě",meaning:"snow"},{char:"雷",pinyin:"léi",meaning:"thunder"}], colloquial: "雨字头", tier: "common", comment: "Rain 雨 — drops in the sky. Weather: 雪, 雷, 雾, 霜." },
  { kangxi: 174,char: "青", form: null, pinyin: "qīng", meaning: "Blue, green, young",  cat: "tools", ex: [{char:"静",pinyin:"jìng",meaning:"quiet"},{char:"靛",pinyin:"diàn",meaning:"indigo"}], colloquial: "青字旁", tier: "common", comment: "Young & green/blue 青. Plants growing: 静, 靛, 情 (with 心)." },
  { kangxi: 175,char: "非", form: null, pinyin: "fēi",  meaning: "Wrong, not",          cat: "actions", ex: [{char:"靠",pinyin:"kào",meaning:"lean"},{char:"靡",pinyin:"mǐ",meaning:"none"}], colloquial: "非字旁", tier: "common", comment: "Two backs turned = wrong 非. Negation: 靠, 靡, 悲." },
  { kangxi: 176,char: "面", form: null, pinyin: "miàn", meaning: "Face",                cat: "people",    ex: [{char:"靥",pinyin:"yè",meaning:"dimple"},{char:"靦",pinyin:"miǎn",meaning:"shy"}], colloquial: "面字旁", tier: "common", comment: "A face 面. Facial expressions: 靥, 靦." },
  { kangxi: 177,char: "革", form: null, pinyin: "gé",   meaning: "Leather, hide",       cat: "tools", ex: [{char:"鞋",pinyin:"xié",meaning:"shoe"},{char:"鞭",pinyin:"biān",meaning:"whip"}], colloquial: "革字旁", tier: "common", comment: "Stretched leather 革. Hides: 鞋, 鞭, 靴." },
  { kangxi: 178,char: "韦", form: "韋", pinyin: "wéi",  meaning: "Tanned leather",      cat: "tools", ex: [{char:"韧",pinyin:"rèn",meaning:"tough"},{char:"韩",pinyin:"hán",meaning:"Korea"}], colloquial: "韦字旁", tier: "extended", comment: "Tanned leather 韦. 韧, 韩." },
  { kangxi: 179,char: "韭", form: null, pinyin: "jiǔ",  meaning: "Leek",                cat: "plants",  ex: [{char:"韮",pinyin:"jiǔ",meaning:"leek"},{char:"韱",pinyin:"xiān",meaning:"wild-onion"}], colloquial: "韭字旁", tier: "extended", comment: "Leeks growing in a row 韭. 韮, 韱." },
  { kangxi: 180,char: "音", form: null, pinyin: "yīn",  meaning: "Sound",               cat: "actions", ex: [{char:"韵",pinyin:"yùn",meaning:"rhyme"},{char:"韶",pinyin:"sháo",meaning:"music"}], colloquial: "音字旁", tier: "common", comment: "Sound 音 — words with a tongue mark. Tones: 韵, 韶, 章." },

  // 181-190
  { kangxi: 181,char: "页", form: "頁", pinyin: "yè",   meaning: "Leaf, page, head",    cat: "people", ex: [{char:"顺",pinyin:"shùn",meaning:"smooth"},{char:"须",pinyin:"xū",meaning:"need"}], colloquial: "页字旁", tier: "common", comment: "A head 页 (originally human head). Head/page: 顺, 须, 顾, 题." },
  { kangxi: 182,char: "风", form: "風", pinyin: "fēng", meaning: "Wind",                cat: "nature",  ex: [{char:"飘",pinyin:"piāo",meaning:"flutter"},{char:"飓",pinyin:"jù",meaning:"hurricane"}], colloquial: "风字旁", tier: "common", comment: "Wind 风 with a worm inside (ancients linked them). 飘, 飓." },
  { kangxi: 183,char: "飞", form: "飛", pinyin: "fēi",  meaning: "Fly",                 cat: "actions", ex: [{char:"飞",pinyin:"fēi",meaning:"fly"},{char:"飜",pinyin:"fān",meaning:"turn-over"}], colloquial: "飞字旁", tier: "common", comment: "Bird taking flight 飞. 翻 (with 羽)." },
  { kangxi: 184,char: "食", form: "饣", pinyin: "shí",  meaning: "Food, eat",           cat: "tools", ex: [{char:"饭",pinyin:"fàn",meaning:"meal"},{char:"馆",pinyin:"guǎn",meaning:"shop"}], colloquial: "食字旁", tier: "basic", comment: "Food in a covered vessel 食. Side form 饣: 饭, 饿, 馆, 饮." },
  { kangxi: 185,char: "首", form: null, pinyin: "shǒu", meaning: "Head, chief",         cat: "people",    ex: [{char:"馗",pinyin:"kuí",meaning:"crossroad"},{char:"馘",pinyin:"guó",meaning:"ear-cut"}], colloquial: "首字旁", tier: "common", comment: "A head with hair 首 — chief. Leadership: 馗." },
  { kangxi: 186,char: "香", form: null, pinyin: "xiāng",meaning: "Fragrant",            cat: "nature",  ex: [{char:"馥",pinyin:"fù",meaning:"fragrance"},{char:"馨",pinyin:"xīn",meaning:"sweet-smell"}], colloquial: "香字旁", tier: "common", comment: "Grain in sun = fragrant 香. Smells: 馥, 馨." },
  { kangxi: 187,char: "马", form: "馬", pinyin: "mǎ",   meaning: "Horse",               cat: "animals",  ex: [{char:"码",pinyin:"mǎ",meaning:"code"},{char:"妈",pinyin:"mā",meaning:"mom"}], colloquial: "马字旁", tier: "basic", comment: "A horse 马 with mane. Equine: 骑, 驾, 验, 妈 (phonetic)." },
  { kangxi: 188,char: "骨", form: null, pinyin: "gǔ",   meaning: "Bone",                cat: "people",    ex: [{char:"骼",pinyin:"gé",meaning:"skeleton"},{char:"髓",pinyin:"suǐ",meaning:"marrow"}], colloquial: "骨字旁", tier: "common", comment: "Bones 骨 with flesh. Skeleton: 骼, 髓, 骸." },
  { kangxi: 189,char: "高", form: null, pinyin: "gāo",  meaning: "Tall, high",          cat: "actions", ex: [{char:"高",pinyin:"gāo",meaning:"tall"},{char:"髚",pinyin:"qiào",meaning:"raised"}], colloquial: "高字旁", tier: "common", comment: "A tall building 高. Height: 髙, 髚." },
  { kangxi: 190,char: "髟", form: null, pinyin: "biāo", meaning: "Long hair",           cat: "people",    ex: [{char:"髮",pinyin:"fà",meaning:"hair"},{char:"髦",pinyin:"máo",meaning:"trendy"}], colloquial: "髟字头", tier: "extended", comment: "Long flowing hair 髟. 髮, 髦, 鬓." },

  // 191-200
  { kangxi: 191,char: "鬥", form: null, pinyin: "dòu",  meaning: "Fight",               cat: "actions", ex: [{char:"鬧",pinyin:"nào",meaning:"noisy"},{char:"鬮",pinyin:"jiū",meaning:"lottery"}], colloquial: "鬥字旁", tier: "extended", comment: "Two warriors fighting 鬥. 鬧, 鬮." },
  { kangxi: 192,char: "鬯", form: null, pinyin: "chàng",meaning: "Sacrificial wine",    cat: "tools", ex: [{char:"鬱",pinyin:"yù",meaning:"gloomy"},{char:"鬱",pinyin:"yù",meaning:"lush"}], colloquial: "鬯字旁", tier: "extended", comment: "Sacrificial wine 鬯. Rare; lives in 鬱." },
  { kangxi: 193,char: "鬲", form: null, pinyin: "lì",   meaning: "Cauldron",            cat: "tools", ex: [{char:"融",pinyin:"róng",meaning:"melt"},{char:"鬵",pinyin:"xún",meaning:"large-pot"}], colloquial: "鬲字旁", tier: "extended", comment: "Tripod cauldron 鬲. 融, 鬵." },
  { kangxi: 194,char: "鬼", form: null, pinyin: "guǐ",  meaning: "Ghost, spirit",       cat: "people", ex: [{char:"魂",pinyin:"hún",meaning:"soul"},{char:"魔",pinyin:"mó",meaning:"demon"}], colloquial: "鬼字旁", tier: "common", comment: "A ghost 鬼 with mask. Spirits: 魂, 魔, 魅." },
  { kangxi: 195,char: "鱼", form: "魚", pinyin: "yú",   meaning: "Fish",                cat: "animals",  ex: [{char:"鲜",pinyin:"xiān",meaning:"fresh"},{char:"鳕",pinyin:"xuě",meaning:"cod"}], colloquial: "鱼字旁", tier: "common", comment: "A fish 鱼 with fins. Aquatic: 鲜, 鳕, 鲸." },
  { kangxi: 196,char: "鸟", form: "鳥", pinyin: "niǎo", meaning: "Bird",                cat: "animals",  ex: [{char:"鸡",pinyin:"jī",meaning:"chicken"},{char:"鸭",pinyin:"yā",meaning:"duck"}], colloquial: "鸟字旁", tier: "common", comment: "A bird 鸟 perched. Avian: 鸡, 鸭, 鹅." },
  { kangxi: 197,char: "卤", form: "鹵", pinyin: "lǔ",   meaning: "Salt, brine",         cat: "tools", ex: [{char:"咸",pinyin:"xián",meaning:"salty"},{char:"鹾",pinyin:"cuó",meaning:"salt"}], colloquial: "卤字旁", tier: "common", comment: "Salt grains in a pan 卤. 咸, 鹾." },
  { kangxi: 198,char: "鹿", form: null, pinyin: "lù",   meaning: "Deer",                cat: "animals",  ex: [{char:"麋",pinyin:"mí",meaning:"elk"},{char:"麒",pinyin:"qí",meaning:"unicorn"}], colloquial: "鹿字旁", tier: "common", comment: "A deer 鹿 with antlers. 麋, 麒." },
  { kangxi: 199,char: "麦", form: "麥", pinyin: "mài",  meaning: "Wheat",               cat: "plants",  ex: [{char:"面",pinyin:"miàn",meaning:"flour"},{char:"麸",pinyin:"fū",meaning:"bran"}], colloquial: "麦字旁", tier: "common", comment: "Wheat plant 麦. 面, 麸." },
  { kangxi: 200,char: "麻", form: null, pinyin: "má",   meaning: "Hemp",                cat: "plants",  ex: [{char:"麽",pinyin:"me",meaning:"-(particle)"},{char:"麾",pinyin:"huī",meaning:"banner"}], colloquial: "麻字旁", tier: "common", comment: "Hemp drying under a roof 麻. 麽, 麾." },

  // 201-214
  { kangxi: 201,char: "黄", form: "黃", pinyin: "huáng",meaning: "Yellow",              cat: "tools", ex: [{char:"黉",pinyin:"hóng",meaning:"school"},{char:"黋",pinyin:"kuàng",meaning:"shining"}], colloquial: "黄字旁", tier: "common", comment: "Yellow 黄 — sash on a person. 黉, 黋." },
  { kangxi: 202,char: "黍", form: null, pinyin: "shǔ",  meaning: "Millet",              cat: "plants",  ex: [{char:"黎",pinyin:"lí",meaning:"multitude"},{char:"黏",pinyin:"nián",meaning:"sticky"}], colloquial: "黍字旁", tier: "extended", comment: "Millet 黍. 黎, 黏." },
  { kangxi: 203,char: "黑", form: null, pinyin: "hēi",  meaning: "Black",               cat: "tools", ex: [{char:"默",pinyin:"mò",meaning:"silent"},{char:"墨",pinyin:"mò",meaning:"ink"}], colloquial: "黑字旁", tier: "common", comment: "Black 黑 — soot above fire. Darkness: 默, 墨, 黛." },
  { kangxi: 204,char: "黹", form: null, pinyin: "zhǐ",  meaning: "Embroidery",          cat: "tools", ex: [{char:"黻",pinyin:"fú",meaning:"pattern"},{char:"黼",pinyin:"fǔ",meaning:"axe-pattern"}], colloquial: "黹字旁", tier: "extended", comment: "Embroidery patterns 黹. 黻, 黼." },
  { kangxi: 205,char: "黾", form: "黽", pinyin: "měng", meaning: "Frog, toad",          cat: "animals",  ex: [{char:"鼋",pinyin:"yuán",meaning:"sea-turtle"},{char:"鼍",pinyin:"tuó",meaning:"alligator"}], colloquial: "黾字旁", tier: "extended", comment: "A frog/toad 黾. 鼋, 鼍." },
  { kangxi: 206,char: "鼎", form: null, pinyin: "dǐng", meaning: "Tripod cauldron",     cat: "tools", ex: [{char:"鼐",pinyin:"nài",meaning:"large-tripod"},{char:"鼒",pinyin:"zī",meaning:"small-tripod"}], colloquial: "鼎字旁", tier: "common", comment: "A three-legged tripod 鼎. Stability: 鼐, 鼒." },
  { kangxi: 207,char: "鼓", form: null, pinyin: "gǔ",   meaning: "Drum",                cat: "tools", ex: [{char:"鼕",pinyin:"dōng",meaning:"drum-sound"},{char:"鼙",pinyin:"pí",meaning:"war-drum"}], colloquial: "鼓字旁", tier: "common", comment: "A drum 鼓. Percussion: 鼕, 鼙." },
  { kangxi: 208,char: "鼠", form: null, pinyin: "shǔ",  meaning: "Rat, mouse",          cat: "animals",  ex: [{char:"鼯",pinyin:"wú",meaning:"flying-squirrel"},{char:"鼹",pinyin:"yǎn",meaning:"mole"}], colloquial: "鼠字旁", tier: "common", comment: "A rat 鼠 with whiskers. 鼯, 鼹." },
  { kangxi: 209,char: "鼻", form: null, pinyin: "bí",   meaning: "Nose",                cat: "people",    ex: [{char:"鼾",pinyin:"hān",meaning:"snore"},{char:"鼽",pinyin:"qiú",meaning:"stuffy-nose"}], colloquial: "鼻字旁", tier: "common", comment: "A nose 鼻 — self plus airflow. 鼾, 鼽." },
  { kangxi: 210,char: "齐", form: "齊", pinyin: "qí",   meaning: "Even, neat",          cat: "actions", ex: [{char:"齋",pinyin:"zhāi",meaning:"vegetarian"},{char:"齏",pinyin:"jī",meaning:"pickled"}], colloquial: "齐字旁", tier: "common", comment: "Even rows of wheat = neat 齐. 齋, 齏." },
  { kangxi: 211,char: "齿", form: "齒", pinyin: "chǐ",  meaning: "Tooth",               cat: "people",    ex: [{char:"龄",pinyin:"líng",meaning:"age"},{char:"龋",pinyin:"qǔ",meaning:"decay"}], colloquial: "齿字旁", tier: "common", comment: "Teeth 齿 — open mouth full of teeth. 龄, 龋." },
  { kangxi: 212,char: "龙", form: "龍", pinyin: "lóng", meaning: "Dragon",              cat: "animals",  ex: [{char:"袭",pinyin:"xí",meaning:"raid"},{char:"龚",pinyin:"gōng",meaning:"surname"}], colloquial: "龙字旁", tier: "common", comment: "A dragon 龙 with arched body. 袭, 龚." },
  { kangxi: 213,char: "龟", form: "龜", pinyin: "guī",  meaning: "Turtle",              cat: "animals",  ex: [{char:"龜",pinyin:"guī",meaning:"turtle"},{char:"鱉",pinyin:"biē",meaning:"soft-turtle"}], colloquial: "龟字旁", tier: "extended", comment: "A turtle 龟 with shell pattern. 龜, 鱉." },
  { kangxi: 214,char: "龠", form: null, pinyin: "yuè",  meaning: "Flute",               cat: "tools", ex: [{char:"龢",pinyin:"hé",meaning:"harmony"},{char:"龣",pinyin:"jué",meaning:"musical-note"}], colloquial: "龠字旁", tier: "extended", comment: "A panpipe / flute 龠. Music: 龢, 龣." },
]

export const TIERS = {
  basic:    { label: "Top 40",  desc: "Most fundamental — start here" },
  top100:   { label: "Top 100", desc: "Common in everyday characters" },
  all:      { label: "All 214", desc: "Complete Kangxi set" },
}

// Filter helpers
export const radicalsByTier = (tier) => {
  if (tier === 'basic')  return allRadicals.filter(r => r.tier === 'basic')
  if (tier === 'top100') return allRadicals.filter(r => r.tier === 'basic' || r.tier === 'common')
  return allRadicals
}

export const CATEGORIES = {
  strokes: { label: "Strokes",  emoji: "笔",  color: "#1f1d1a" },
  people:  { label: "People",   emoji: "人",  color: "#9b2226" },
  nature:  { label: "Nature",   emoji: "山",  color: "#2d6a4f" },
  plants:  { label: "Plants",   emoji: "木",  color: "#6b8e23" },
  animals: { label: "Animals",  emoji: "鸟",  color: "#8b5a2b" },
  tools:   { label: "Tools",    emoji: "器",  color: "#7c5a1e" },
  actions: { label: "Actions",  emoji: "动",  color: "#344e8b" },
}

export const CAT_COLORS = {
  strokes: { bg: "#ececec", accent: "#1f1d1a", light: "#cfcfcf", text: "#0f0e0c" },
  people:  { bg: "#fce4e4", accent: "#9b2226", light: "#f5c6c6", text: "#5a0e12" },
  nature:  { bg: "#e8f5e9", accent: "#2d6a4f", light: "#c8e6c9", text: "#1b4332" },
  plants:  { bg: "#eef3d8", accent: "#6b8e23", light: "#d4dfa3", text: "#3d4f14" },
  animals: { bg: "#f3e3d0", accent: "#8b5a2b", light: "#e1c39b", text: "#4a2f15" },
  tools:   { bg: "#fdf3e3", accent: "#7c5a1e", light: "#f5deb3", text: "#4a3200" },
  actions: { bg: "#e8eaf6", accent: "#344e8b", light: "#c5cae9", text: "#1a237e" },
}

export const polarXY = (a, r) => ({
  x: Math.cos(a * Math.PI / 180) * r,
  y: Math.sin(a * Math.PI / 180) * r,
})

export const useRadicals = () => ({ allRadicals, CATEGORIES, CAT_COLORS, TIERS, radicalsByTier, polarXY })
