// Source: HSK Standard Course 3, lessons 11-15 (book pp. 90-133;
// PDF pp. 106-149). Chinese texts, ordering, vocabulary, and grammar topics
// follow the supplied textbook. English line translations are study glosses.

export const HSK3_LESSONS_11_15 = [
  {
    no: 11,
    bookPage: 90,
    pdfPage: 106,
    han: '别忘了把空调关了',
    pinyin: 'Bié wàngle bǎ kōngtiáo guān le',
    en: "Don't forget to turn off the air conditioner",
    focus: '“把”字句1：A把B + V + …… · 概数的表达2：左右',
    texts: [
      {
        title: '在教室 · In the classroom',
        lines: [
          { s: 'A', speaker: '小明', c: '我先走了。', p: 'Wǒ xiān zǒu le.', en: "I'm leaving now." },
          { s: 'B', speaker: '同学', c: '你去哪儿？', p: 'Nǐ qù nǎr?', en: 'Where are you going?' },
          { s: 'A', speaker: '小明', c: '我去图书馆借本书。', p: 'Wǒ qù túshūguǎn jiè běn shū.', en: "I'm going to the library to borrow a book." },
          { s: 'B', speaker: '同学', c: '帮我把这本词典还了吧。', p: 'Bāng wǒ bǎ zhè běn cídiǎn huánle ba.', en: 'Please return this dictionary for me.' },
          { s: 'A', speaker: '小明', c: '好，等一会儿你离开教室的时候，记得把灯关了。', p: 'Hǎo, děng yíhuìr nǐ lí kāi jiàoshì de shíhou, jìde bǎ dēng guān le.', en: 'All right. Remember to turn off the light when you leave the classroom later.' },
          { s: 'B', speaker: '同学', c: '好的，放心吧。', p: 'Hǎo de, fàng xīn ba.', en: "Okay, don't worry." },
        ],
      },
      {
        title: '在会议室 · In the conference room',
        lines: [
          { s: 'A', speaker: '周明', c: '会议结束后，别忘记把空调关了。', p: 'Huìyì jiéshù hòu, bié wàngjì bǎ kōngtiáo guān le.', en: "After the meeting, don't forget to turn off the air conditioner." },
          { s: 'B', speaker: '小丽', c: '好的。王经理两点左右来了个电话。', p: 'Hǎo de. Wáng jīnglǐ liǎng diǎn zuǒyòu láile ge diànhuà.', en: 'Okay. Manager Wang called at around two.' },
          { s: 'A', speaker: '周明', c: '他已经到北京了？', p: 'Tā yǐjīng dào Běijīng le?', en: 'Has he already arrived in Beijing?' },
          { s: 'B', speaker: '小丽', c: '是的，他正坐地铁来我们公司呢。', p: 'Shì de, tā zhèng zuò dìtiě lái wǒmen gōngsī ne.', en: "Yes. He's taking the subway to our company now." },
          { s: 'A', speaker: '周明', c: '等他到了就告诉我。', p: 'Děng tā dàole jiù gàosu wǒ.', en: 'Tell me as soon as he arrives.' },
        ],
      },
      {
        title: '在客厅 · In the living room',
        lines: [
          { s: 'A', speaker: '妈妈', c: '还差一双筷子，你去拿一下。', p: 'Hái chà yì shuāng kuàizi, nǐ qù ná yíxià.', en: 'We still need one pair of chopsticks. Go and get them.' },
          { s: 'B', speaker: '儿子', c: '今天怎么做了这么多菜？', p: 'Jīntiān zěnme zuòle zhème duō cài?', en: 'Why did you make so many dishes today?' },
          { s: 'A', speaker: '妈妈', c: '今天是你爸爸的生日。', p: 'Jīntiān shì nǐ bàba de shēngrì.', en: "Today is your father's birthday." },
          { s: 'B', speaker: '儿子', c: '真的啊？我把爸爸的生日忘了。那我们今天喝点儿啤酒吧。', p: 'Zhēn de a? Wǒ bǎ bàba de shēngrì wàng le. Nà wǒmen jīntiān hē diǎnr píjiǔ ba.', en: "Really? I forgot Dad's birthday. Then let's drink some beer today." },
          { s: 'A', speaker: '妈妈', c: '医生说你爸爸一口酒都不能喝，别让他看见酒瓶子。', p: 'Yīshēng shuō nǐ bàba yì kǒu jiǔ dōu bù néng hē, bié ràng tā kànjiàn jiǔ píngzi.', en: "The doctor said your father cannot drink even a mouthful. Don't let him see the beer bottle." },
        ],
      },
      {
        title: '课文 11-4 · Text 11-4',
        lines: [
          { s: 'N', speaker: '旁白', c: '这个笔记本电脑我去年买的时候要五千块左右，现在便宜多了。', p: 'Zhège bǐjìběn diànnǎo wǒ qùnián mǎi de shíhou yào wǔ qiān kuài zuǒyòu, xiànzài piányi duō le.', en: 'This laptop cost around five thousand yuan when I bought it last year; now it is much cheaper.' },
          { s: 'N', speaker: '旁白', c: '我想把这个电脑卖了，再买一个更好的。', p: 'Wǒ xiǎng bǎ zhège diànnǎo mài le, zài mǎi yí ge gèng hǎo de.', en: 'I want to sell this computer and buy a better one.' },
          { s: 'N', speaker: '旁白', c: '现在我每天起床后的第一件事就是打开电脑，看电子邮件。', p: 'Xiànzài wǒ měi tiān qǐ chuáng hòu de dì yí jiàn shì jiù shì dǎ kāi diànnǎo, kàn diànzǐ yóujiàn.', en: 'Now the first thing I do after getting up each day is turn on the computer and check my email.' },
          { s: 'N', speaker: '旁白', c: '我已经很少写信，也很少用笔写字，已经习惯用电脑来学习和工作了。', p: 'Wǒ yǐjīng hěn shǎo xiě xìn, yě hěn shǎo yòng bǐ xiě zì, yǐjīng xíguàn yòng diànnǎo lái xuéxí hé gōngzuò le.', en: 'I rarely write letters or write with a pen now; I am used to using a computer to study and work.' },
          { s: 'N', speaker: '旁白', c: '哪一天突然没有了电脑，我们怎么办呢？', p: 'Nǎ yì tiān tūrán méiyǒule diànnǎo, wǒmen zěnme bàn ne?', en: 'What would we do if one day computers suddenly disappeared?' },
        ],
      },
    ],
    vocab: [
      { c: '图书馆', p: 'túshūguǎn', pos: 'n.', en: 'library' },
      { c: '借', p: 'jiè', pos: 'v.', en: 'to borrow; to lend' },
      { c: '词典', p: 'cídiǎn', pos: 'n.', en: 'dictionary' },
      { c: '还', p: 'huán', pos: 'v.', en: 'to return' },
      { c: '灯', p: 'dēng', pos: 'n.', en: 'light; lamp' },
      { c: '会议', p: 'huìyì', pos: 'n.', en: 'meeting; conference' },
      { c: '结束', p: 'jiéshù', pos: 'v.', en: 'to end; to finish' },
      { c: '忘记', p: 'wàngjì', pos: 'v.', en: 'to forget' },
      { c: '空调', p: 'kōngtiáo', pos: 'n.', en: 'air conditioner' },
      { c: '关', p: 'guān', pos: 'v.', en: 'to turn off; to close' },
      { c: '地铁', p: 'dìtiě', pos: 'n.', en: 'subway' },
      { c: '双', p: 'shuāng', pos: 'm.', en: 'pair' },
      { c: '筷子', p: 'kuàizi', pos: 'n.', en: 'chopsticks' },
      { c: '啤酒', p: 'píjiǔ', pos: 'n.', en: 'beer' },
      { c: '口', p: 'kǒu', pos: 'm.', en: 'mouthful' },
      { c: '瓶子', p: 'píngzi', pos: 'n.', en: 'bottle' },
      { c: '笔记本（电脑）', p: 'bǐjìběn (diànnǎo)', pos: 'n.', en: 'notebook; laptop' },
      { c: '电子邮件', p: 'diànzǐ yóujiàn', pos: 'n.', en: 'email' },
      { c: '习惯', p: 'xíguàn', pos: 'v./n.', en: 'to be used to; habit' },
    ],
    notes: [
      {
        title: '“把”字句1：A把B+V+…… · The Ba-Sentence 1: A把B + V + ……',
        summary: 'Use A把B + V when an action disposes of a definite or known person or thing. A is the agent and B is the affected object. Negators and modal verbs go before 把.',
        examples: [
          { c: '帮我把这本词典还了。', p: 'Bāng wǒ bǎ zhè běn cídiǎn huánle.', en: 'Return this dictionary for me.' },
          { c: '你把灯关了吧。', p: 'Nǐ bǎ dēng guān le ba.', en: 'Please turn off the light.' },
          { c: '我不能把电脑给你。', p: 'Wǒ bù néng bǎ diànnǎo gěi nǐ.', en: "I can't give you the computer." },
        ],
      },
      {
        title: '概数的表达2：左右 · Expression of Approximate Numbers 2: 左右',
        summary: '左右 follows a number to mean “approximately” or “around”.',
        examples: [
          { c: '周末我一般十点左右起床。', p: 'Zhōumò wǒ yìbān shí diǎn zuǒyòu qǐchuáng.', en: 'I usually get up around ten on weekends.' },
          { c: '我们公司有五百人左右。', p: 'Wǒmen gōngsī yǒu wǔ bǎi rén zuǒyòu.', en: 'Our company has around five hundred people.' },
          { c: '王经理两点左右来了个电话。', p: 'Wáng jīnglǐ liǎng diǎn zuǒyòu láile ge diànhuà.', en: 'Manager Wang called at around two.' },
        ],
      },
    ],
  },
  {
    no: 12,
    bookPage: 98,
    pdfPage: 114,
    han: '把重要的东西放在我这儿吧',
    pinyin: 'Bǎ zhòngyào de dōngxi fàng zài wǒ zhèr ba',
    en: 'Leave the important items with me',
    focus: '“才”和“就” · “把”字句2：A把B + V + 在/到/给……',
    texts: [
      {
        title: '在家 · At home',
        lines: [
          { s: 'A', speaker: '小丽', c: '今天太阳从西边出来了吗？', p: 'Jīntiān tàiyáng cóng xībian chūlai le ma?', en: 'Did the sun rise in the west today?' },
          { s: 'B', speaker: '小刚', c: '怎么了？', p: 'Zěnme le?', en: "What's the matter?" },
          { s: 'A', speaker: '小丽', c: '你怎么这么早就要睡觉了？以前都要12点以后才睡觉。', p: 'Nǐ zěnme zhème zǎo jiù yào shuì jiào le? Yǐqián dōu yào shí’èr diǎn yǐhòu cái shuì jiào.', en: 'Why are you going to bed so early? You used to go to sleep only after twelve.' },
          { s: 'B', speaker: '小刚', c: '我明天8点就要到公司。', p: 'Wǒ míngtiān bā diǎn jiù yào dào gōngsī.', en: 'I have to be at the company by eight tomorrow.' },
          { s: 'A', speaker: '小丽', c: '有事吗？', p: 'Yǒu shì ma?', en: 'Is something happening?' },
          { s: 'B', speaker: '小刚', c: '经理生气了，他告诉我，明天8点不到，以后就别来了。', p: 'Jīnglǐ shēng qì le, tā gàosu wǒ, míngtiān bā diǎn bú dào, yǐhòu jiù bié lái le.', en: 'The manager got angry. He told me that if I am not there by eight tomorrow, I should not come again.' },
        ],
      },
      {
        title: '在家 · At home',
        lines: [
          { s: 'A', speaker: '小刚', c: '我要跟周经理去外地办事，明天的飞机。', p: 'Wǒ yào gēn Zhōu jīnglǐ qù wàidì bàn shì, míngtiān de fēijī.', en: "I'm going out of town on business with Manager Zhou. Our flight is tomorrow." },
          { s: 'B', speaker: '小丽', c: '那我帮你把衣服放到行李箱里吧。什么时候回来？', p: 'Nà wǒ bāng nǐ bǎ yīfu fàngdào xínglixiāng li ba. Shénme shíhou huílai?', en: 'Then I will put your clothes in the suitcase for you. When will you be back?' },
          { s: 'A', speaker: '小刚', c: '一个星期就回来。', p: 'Yí ge xīngqī jiù huílai.', en: "I'll be back in just one week." },
          { s: 'B', speaker: '小丽', c: '啊？一个星期以后才回来？', p: 'A? Yí ge xīngqī yǐhòu cái huílai?', en: 'What? You will not be back until a week from now?' },
          { s: 'A', speaker: '小刚', c: '你要自己照顾好自己，我已经给你准备好吃的和喝的了。', p: 'Nǐ yào zìjǐ zhàogu hǎo zìjǐ, wǒ yǐjīng gěi nǐ zhǔnbèi hǎo chī de hé hē de le.', en: 'Take good care of yourself. I have already prepared food and drinks for you.' },
          { s: 'B', speaker: '小丽', c: '好吧。我已经把我的照片放在你的包里了。', p: 'Hǎo ba. Wǒ yǐjīng bǎ wǒ de zhàopiàn fàng zài nǐ de bāo li le.', en: 'All right. I have already put my photo in your bag.' },
        ],
      },
      {
        title: '在机场 · At the airport',
        lines: [
          { s: 'A', speaker: '周明', c: '你怎么才来？', p: 'Nǐ zěnme cái lái?', en: 'Why are you only arriving now?' },
          { s: 'B', speaker: '小刚', c: '对不起，周经理，来机场的路上我才发现忘带护照了。', p: 'Duìbuqǐ, Zhōu jīnglǐ, lái jīchǎng de lùshang wǒ cái fāxiàn wàng dài hùzhào le.', en: 'Sorry, Manager Zhou. On the way to the airport I discovered that I had forgotten my passport.' },
          { s: 'A', speaker: '周明', c: '快点儿吧，飞机就要起飞了。', p: 'Kuài diǎnr ba, fēijī jiù yào qǐfēi le.', en: 'Hurry up. The plane is about to take off.' },
          { s: 'B', speaker: '小刚', c: '您有钱吗？司机把我送到机场的时候，我才发现忘记带钱包了。', p: 'Nín yǒu qián ma? Sījī bǎ wǒ sòng dào jīchǎng de shíhou, wǒ cái fāxiàn wàngjì dài qiánbāo le.', en: 'Do you have any money? When the driver brought me to the airport, I realized that I had forgotten my wallet.' },
          { s: 'A', speaker: '周明', c: '我看你还是把重要的东西放在我这儿吧。', p: 'Wǒ kàn nǐ háishi bǎ zhòngyào de dōngxi fàng zài wǒ zhèr ba.', en: 'I think you had better leave the important things with me.' },
        ],
      },
      {
        title: '课文 12-4 · Text 12-4',
        lines: [
          { s: 'N', speaker: '旁白', c: '我是一个中学老师，教学生画画儿。', p: 'Wǒ shì yí ge zhōngxué lǎoshī, jiāo xuésheng huà huàr.', en: 'I am a middle-school teacher, and I teach students to draw.' },
          { s: 'N', speaker: '旁白', c: '每次下课前，我都会把下次学生需要带的东西写在黑板上，但是每次上课时，总会有学生忘了拿铅笔，所以我有点儿生气，不是因为他们没带铅笔，是因为他们没有好的学习习惯。', p: 'Měi cì xià kè qián, wǒ dōu huì bǎ xià cì xuésheng xūyào dài de dōngxi xiě zài hēibǎn shang, dànshi měi cì shàng kè shí, zǒng huì yǒu xuésheng wàngle ná qiānbǐ, suǒyǐ wǒ yǒudiǎnr shēng qì, bú shì yīnwèi tāmen méi dài qiānbǐ, shì yīnwèi tāmen méiyǒu hǎo de xuéxí xíguàn.', en: 'Before each class ends, I write on the blackboard what students need to bring next time. Yet someone always forgets a pencil, so I get a little angry - not because they did not bring one, but because they lack good study habits.' },
        ],
      },
    ],
    vocab: [
      { c: '太阳', p: 'tàiyáng', pos: 'n.', en: 'sun' },
      { c: '西', p: 'xī', pos: 'n.', en: 'west' },
      { c: '生气', p: 'shēng qì', pos: 'v.', en: 'to be angry' },
      { c: '行李箱', p: 'xínglixiāng', pos: 'n.', en: 'luggage; suitcase' },
      { c: '自己', p: 'zìjǐ', pos: 'pron.', en: 'self' },
      { c: '包', p: 'bāo', pos: 'n.', en: 'bag; sack' },
      { c: '发现', p: 'fāxiàn', pos: 'v.', en: 'to discover' },
      { c: '护照', p: 'hùzhào', pos: 'n.', en: 'passport' },
      { c: '起飞', p: 'qǐfēi', pos: 'v.', en: 'to take off (aircraft)' },
      { c: '司机', p: 'sījī', pos: 'n.', en: 'driver' },
      { c: '教', p: 'jiāo', pos: 'v.', en: 'to teach' },
      { c: '画', p: 'huà', pos: 'v./n.', en: 'to draw; to paint; drawing; painting' },
      { c: '需要', p: 'xūyào', pos: 'v.', en: 'to need' },
      { c: '黑板', p: 'hēibǎn', pos: 'n.', en: 'blackboard' },
    ],
    notes: [
      {
        title: '“才”和“就” · Comparison of “才” and “就”',
        summary: 'Before a verb, 就 presents an action as early, fast, or smooth; 才 presents it as late, slow, or achieved with difficulty.',
        examples: [
          { c: '我早上五点就起床了。', p: 'Wǒ zǎoshang wǔ diǎn jiù qǐchuáng le.', en: 'I got up as early as five in the morning.' },
          { c: '八点上课，他九点才起床。', p: 'Bā diǎn shàng kè, tā jiǔ diǎn cái qǐchuáng.', en: 'Class starts at eight, but he did not get up until nine.' },
          { c: '来机场的路上我才发现忘带护照了。', p: 'Lái jīchǎng de lùshang wǒ cái fāxiàn wàng dài hùzhào le.', en: 'Only on the way to the airport did I discover that I had forgotten my passport.' },
        ],
      },
      {
        title: '“把”字句2：A把B+V+在/到/给…… · The Ba-Sentence 2: A把B + V + 在/到/给……',
        summary: 'A 把 sentence can show that an action changes a definite object’s location with 在/到, or transfers it to a recipient with 给.',
        examples: [
          { c: '我把照片放在你包里了。', p: 'Wǒ bǎ zhàopiàn fàng zài nǐ bāo li le.', en: 'I put the photo in your bag.' },
          { c: '老师把作业放在桌子上了。', p: 'Lǎoshī bǎ zuòyè fàng zài zhuōzi shang le.', en: 'The teacher put the homework on the desk.' },
          { c: '你帮我把这本书带给小刚。', p: 'Nǐ bāng wǒ bǎ zhè běn shū dài gěi Xiǎogāng.', en: 'Please take this book to Xiaogang for me.' },
        ],
      },
    ],
  },
  {
    no: 13,
    bookPage: 107,
    pdfPage: 123,
    han: '我是走回来的',
    pinyin: 'Wǒ shì zǒu huílai de',
    en: 'I walked back',
    focus: '复合趋向补语 · 一边……一边……',
    texts: [
      {
        title: '在家 · At home',
        lines: [
          { s: 'A', speaker: '小丽', c: '你终于回来了！从哪儿买回来这么多东西啊？', p: 'Nǐ zhōngyú huílai le! Cóng nǎr mǎi huílai zhème duō dōngxi a?', en: 'You finally came back! Where did you buy all these things?' },
          { s: 'B', speaker: '小刚', c: '都是从那边的商店买回来的。', p: 'Dōu shì cóng nà bian de shāngdiàn mǎi huílai de.', en: 'They were all bought at the shop over there.' },
          { s: 'A', speaker: '小丽', c: '怎么还买红酒回来了？谁喝啊？', p: 'Zěnme hái mǎi hóngjiǔ huílai le? Shéi hē a?', en: 'Why did you also bring back red wine? Who is going to drink it?' },
          { s: 'B', speaker: '小刚', c: '这是给爷爷的礼物，明天我们一起送过去，看看爷爷奶奶。', p: 'Zhè shì gěi yéye de lǐwù, míngtiān wǒmen yìqǐ sòng guòqu, kànkan yéye nǎinai.', en: 'It is a gift for Grandpa. Tomorrow we will take it over and visit Grandpa and Grandma.' },
          { s: 'A', speaker: '小丽', c: '那我的礼物呢？快拿出来让我看看。', p: 'Nà wǒ de lǐwù ne? Kuài ná chūlai ràng wǒ kànkan.', en: 'Then where is my gift? Take it out and let me see.' },
          { s: 'B', speaker: '小刚', c: '我不是已经回来了吗？', p: 'Wǒ bú shì yǐjīng huílai le ma?', en: "Haven't I already come back?" },
        ],
      },
      {
        title: '在家 · At home',
        lines: [
          { s: 'A', speaker: '小丽', c: '我今天看见你和一个女的进了咖啡店，她是谁啊？', p: 'Wǒ jīntiān kànjiàn nǐ hé yí ge nǚ de jìnle kāfēidiàn, tā shì shéi a?', en: 'Today I saw you enter a coffee shop with a woman. Who was she?' },
          { s: 'B', speaker: '小刚', c: '她是我今天在路上遇到的一个老同学。', p: 'Tā shì wǒ jīntiān zài lùshang yùdào de yí ge lǎo tóngxué.', en: 'She is an old classmate I ran into on the street today.' },
          { s: 'A', speaker: '小丽', c: '你们就一起去喝咖啡了？', p: 'Nǐmen jiù yìqǐ qù hē kāfēi le?', en: 'So you went for coffee together?' },
          { s: 'B', speaker: '小刚', c: '是啊，一边喝咖啡一边说了些过去的事。', p: 'Shì a, yìbiān hē kāfēi yìbiān shuōle xiē guòqu de shì.', en: 'Yes. We drank coffee while talking about things from the past.' },
          { s: 'A', speaker: '小丽', c: '你回来得这么晚，是说了很多过去的事吗？', p: 'Nǐ huílai de zhème wǎn, shì shuōle hěn duō guòqu de shì ma?', en: 'You came back so late - did you talk about a lot of the past?' },
          { s: 'B', speaker: '小刚', c: '不是。没有公共汽车了，我是走回来的。', p: 'Bú shì. Méiyǒu gōnggòng qìchē le, wǒ shì zǒu huílai de.', en: 'No. There were no buses, so I walked back.' },
        ],
      },
      {
        title: '在打电话 · On the phone',
        lines: [
          { s: 'A', speaker: '同事', c: '小丽，周末你一般跟小刚出去看电影吗？', p: 'Xiǎolì, zhōumò nǐ yìbān gēn Xiǎogāng chūqu kàn diànyǐng ma?', en: 'Xiaoli, do you usually go out to see a film with Xiaogang on weekends?' },
          { s: 'B', speaker: '小丽', c: '我很少去电影院看电影，我更愿意在家看电视。', p: 'Wǒ hěn shǎo qù diànyǐngyuàn kàn diànyǐng, wǒ gèng yuànyì zài jiā kàn diànshì.', en: 'I rarely go to the cinema. I would rather watch television at home.' },
          { s: 'A', speaker: '同事', c: '看电视有什么意思啊？', p: 'Kàn diànshì yǒu shénme yìsi a?', en: "What's interesting about watching television?" },
          { s: 'B', speaker: '小丽', c: '可以一边吃一边看，坐久了还可以站起来休息一会儿。', p: 'Kěyǐ yìbiān chī yìbiān kàn, zuò jiǔ le hái kěyǐ zhàn qǐlai xiūxi yíhuìr.', en: 'You can eat while watching, and after sitting for a long time you can stand up and rest for a while.' },
          { s: 'A', speaker: '同事', c: '你应该多出去走走，这样你们的生活会更有意思。', p: 'Nǐ yīnggāi duō chūqu zǒuzou, zhèyàng nǐmen de shēnghuó huì gèng yǒu yìsi.', en: 'You should go out more. That would make your lives more interesting.' },
          { s: 'B', speaker: '小丽', c: '有他在，我的生活已经很有意思了。', p: 'Yǒu tā zài, wǒ de shēnghuó yǐjīng hěn yǒu yìsi le.', en: 'With him around, my life is already very interesting.' },
        ],
      },
      {
        title: '课文 13-4 · Text 13-4',
        lines: [
          { s: 'N', speaker: '旁白', c: '刚结婚的时候，我丈夫是中学老师，他喜欢每天早上起床后，一边吃早饭一边看报纸。', p: 'Gāng jié hūn de shíhou, wǒ zhàngfu shì zhōngxué lǎoshī, tā xǐhuan měi tiān zǎoshang qǐ chuáng hòu, yìbiān chī zǎofàn yìbiān kàn bàozhǐ.', en: 'When we had just married, my husband was a middle-school teacher. Every morning after getting up, he liked reading the newspaper while eating breakfast.' },
          { s: 'N', speaker: '旁白', c: '十年过去了，现在他已经是校长了，因为太忙，每天早上我起床后都看不到他，晚上很晚他才回到家。', p: 'Shí nián guòqu le, xiànzài tā yǐjīng shì xiàozhǎng le, yīnwèi tài máng, měi tiān zǎoshang wǒ qǐ chuáng hòu dōu kàn bu dào tā, wǎnshang hěn wǎn tā cái huí dào jiā.', en: 'Ten years have passed and now he is a headmaster. He is so busy that he is gone before I get up and returns home very late.' },
          { s: 'N', speaker: '旁白', c: '我真怕他累坏了。', p: 'Wǒ zhēn pà tā lèihuài le.', en: 'I am truly afraid that he will wear himself out.' },
          { s: 'N', speaker: '旁白', c: '希望他能少一些会议，多一些休息，可以经常和我还有孩子在一起。', p: 'Xīwàng tā néng shǎo yìxiē huìyì, duō yìxiē xiūxi, kěyǐ jīngcháng hé wǒ hái yǒu háizi zài yìqǐ.', en: 'I hope he can have fewer meetings and more rest, and spend time with me and our child more often.' },
        ],
      },
    ],
    vocab: [
      { c: '终于', p: 'zhōngyú', pos: 'adv.', en: 'finally' },
      { c: '爷爷', p: 'yéye', pos: 'n.', en: 'grandfather' },
      { c: '礼物', p: 'lǐwù', pos: 'n.', en: 'gift; present' },
      { c: '奶奶', p: 'nǎinai', pos: 'n.', en: 'grandmother' },
      { c: '遇到', p: 'yùdào', pos: 'v.', en: 'to come across; to run into' },
      { c: '一边', p: 'yìbiān', pos: 'adv.', en: 'indicating two actions happening at the same time' },
      { c: '过去', p: 'guòqu', pos: 'n.', en: 'past' },
      { c: '一般', p: 'yìbān', pos: 'adj.', en: 'general; usual' },
      { c: '愿意', p: 'yuànyì', pos: 'v.', en: 'would like to' },
      { c: '起来', p: 'qǐlai', pos: 'v.', en: 'indicating an upward movement; to rise' },
      { c: '应该', p: 'yīnggāi', pos: 'v.', en: 'should' },
      { c: '生活', p: 'shēnghuó', pos: 'n.', en: 'life', supplementary: true },
      { c: '校长', p: 'xiàozhǎng', pos: 'n.', en: 'headmaster' },
      { c: '坏', p: 'huài', pos: 'adj.', en: 'broken; ruined' },
      { c: '经常', p: 'jīngcháng', pos: 'adv.', en: 'often' },
    ],
    notes: [
      {
        title: '复合趋向补语 · Compound Complements of Direction',
        summary: 'A verb plus a simple directional complement forms a compound directional complement. Place objects precede 来/去; ordinary objects may come before or after it, but completed actions usually place the object after 来/去.',
        examples: [
          { c: '老师拿出一本书来。', p: 'Lǎoshī ná chū yì běn shū lái.', en: 'The teacher took out a book.' },
          { c: '老师走进教室来。', p: 'Lǎoshī zǒu jìn jiàoshì lái.', en: 'The teacher walked into the classroom.' },
          { c: '爸爸从国外带回来一些礼物。', p: 'Bàba cóng guówài dài huílai yìxiē lǐwù.', en: 'Dad brought some gifts back from abroad.' },
        ],
      },
      {
        title: '一边……一边…… · The Structure “一边……一边……”',
        summary: '一边……一边…… shows that two actions happen at the same time. The second 一边 may be omitted.',
        examples: [
          { c: '妈妈一边唱歌一边做饭。', p: 'Māma yìbiān chànggē yìbiān zuòfàn.', en: 'Mum sings while cooking.' },
          { c: '老师边说边笑。', p: 'Lǎoshī biān shuō biān xiào.', en: 'The teacher talks and laughs at the same time.' },
          { c: '我丈夫喜欢一边吃早饭一边看报纸。', p: 'Wǒ zhàngfu xǐhuan yìbiān chī zǎofàn yìbiān kàn bàozhǐ.', en: 'My husband likes reading the newspaper while eating breakfast.' },
        ],
      },
    ],
  },
  {
    no: 14,
    bookPage: 116,
    pdfPage: 132,
    han: '你把水果拿过来',
    pinyin: 'Nǐ bǎ shuǐguǒ ná guòlai',
    en: 'Please bring the fruit here',
    focus: '“把”字句3：A把B + V + 结果补语/趋向补语 · 先……，再/又……，然后……',
    texts: [
      {
        title: '在家 · At home',
        lines: [
          { s: 'A', speaker: '周太太', c: '客人就要来了，你怎么还不打扫房间啊？', p: 'Kèrén jiù yào lái le, nǐ zěnme hái bù dǎsǎo fángjiān a?', en: 'The guests are about to arrive. Why have you still not cleaned the room?' },
          { s: 'B', speaker: '周明', c: '别着急，我让孩子们打扫呢，客人来的时候，他们会把房间打扫干净。', p: 'Bié zháo jí, wǒ ràng háizimen dǎsǎo ne, kèrén lái de shíhou, tāmen huì bǎ fángjiān dǎsǎo gānjìng.', en: "Don't worry. I have the children cleaning it; by the time the guests arrive, they will have cleaned the room." },
          { s: 'A', speaker: '周太太', c: '那你也不能看电视啊。', p: 'Nà nǐ yě bù néng kàn diànshì a.', en: "But you can't just watch television either." },
          { s: 'B', speaker: '周明', c: '你让我做什么？', p: 'Nǐ ràng wǒ zuò shénme?', en: 'What do you want me to do?' },
          { s: 'A', speaker: '周太太', c: '先把茶和杯子放好，然后把冰箱里的西瓜拿出来。', p: 'Xiān bǎ chá hé bēizi fànghǎo, ránhòu bǎ bīngxiāng li de xīguā ná chūlai.', en: 'First set out the tea and cups, then take the watermelon out of the refrigerator.' },
          { s: 'B', speaker: '周明', c: '太热了，我还是先把空调打开吧。', p: 'Tài rè le, wǒ háishi xiān bǎ kōngtiáo dǎ kāi ba.', en: 'It is too hot. I had better turn on the air conditioner first.' },
        ],
      },
      {
        title: '在打电话 · On the phone',
        lines: [
          { s: 'A', speaker: '同事', c: '你在忙什么呢？刚才打你的手机你也不接。', p: 'Nǐ zài máng shénme ne? Gāngcái dǎ nǐ de shǒujī nǐ yě bù jiē.', en: 'What are you busy with? I called your mobile just now, but you did not answer.' },
          { s: 'B', speaker: '小刚', c: '对不起，我刚洗了个澡，没听见。有什么事吗？', p: 'Duìbuqǐ, wǒ gāng xǐle ge zǎo, méi tīngjiàn. Yǒu shénme shì ma?', en: 'Sorry, I was taking a shower and did not hear it. What is it?' },
          { s: 'A', speaker: '同事', c: '我想问问你公司里的一些事情。', p: 'Wǒ xiǎng wènwen nǐ gōngsī li de yìxiē shìqing.', en: 'I want to ask you about some things at your company.' },
          { s: 'B', speaker: '小刚', c: '你先等一下，我去把电视关了。', p: 'Nǐ xiān děng yíxià, wǒ qù bǎ diànshì guān le.', en: 'Wait a moment. I will go turn off the television.' },
          { s: 'A', speaker: '同事', c: '没关系，你先把电视节目看完吧，然后再给我回电话。', p: 'Méi guānxi, nǐ xiān bǎ diànshì jiémù kànwán ba, ránhòu zài gěi wǒ huí diànhuà.', en: "That's all right. Finish watching the television programme first, then call me back." },
        ],
      },
      {
        title: '在小明家 · At Xiaoming’s home',
        lines: [
          { s: 'A', speaker: '同学', c: '今晚的月亮真漂亮，像白色的盘子一样。', p: 'Jīn wǎn de yuèliang zhēn piàoliang, xiàng báisè de pánzi yíyàng.', en: 'The moon is beautiful tonight, like a white plate.' },
          { s: 'B', speaker: '小明', c: '是啊，外边也不刮风，我们坐在外边一边看月亮一边吃东西，怎么样？', p: 'Shì a, wàibian yě bù guā fēng, wǒmen zuò zài wàibian yìbiān kàn yuèliang yìbiān chī dōngxi, zěnmeyàng?', en: 'Yes, and it is not windy. How about sitting outside, watching the moon while we eat?' },
          { s: 'A', speaker: '同学', c: '好啊，我先把桌椅搬出去，然后你把水果拿过来，我们听叔叔阿姨讲讲他们年轻时候的故事。', p: 'Hǎo a, wǒ xiān bǎ zhuōyǐ bān chūqu, ránhòu nǐ bǎ shuǐguǒ ná guòlai, wǒmen tīng shūshu āyí jiǎngjiang tāmen niánqīng shíhou de gùshi.', en: 'Great. I will move the table and chairs outside first, then you bring the fruit, and we can listen to your aunt and uncle tell stories from when they were young.' },
          { s: 'B', speaker: '小明', c: '太好了！记得给大山打个电话，让他马上过来。', p: 'Tài hǎo le! Jìde gěi Dàshān dǎ ge diànhuà, ràng tā mǎshàng guòlai.', en: 'Great! Remember to call Dashan and ask him to come over right away.' },
          { s: 'A', speaker: '同学', c: '不用打了，你听外边的声音，一定是大山。', p: 'Búyòng dǎ le, nǐ tīng wàibian de shēngyīn, yídìng shì Dàshān.', en: "No need. Listen to the sound outside - it must be Dashan." },
        ],
      },
      {
        title: '课文 14-4 · Text 14-4',
        lines: [
          { s: 'N', speaker: '旁白', c: '你吃过水果饭吗？', p: 'Nǐ chī guo shuǐguǒ fàn ma?', en: 'Have you ever eaten fruit rice?' },
          { s: 'N', speaker: '旁白', c: '你在饭馆的菜单上见过水果饭吗？', p: 'Nǐ zài fànguǎnr de càidān shang jiàn guo shuǐguǒ fàn ma?', en: 'Have you seen fruit rice on a restaurant menu?' },
          { s: 'N', speaker: '旁白', c: '你想学着做水果饭吗？', p: 'Nǐ xiǎng xuézhe zuò shuǐguǒ fàn ma?', en: 'Would you like to learn to make it?' },
          { s: 'N', speaker: '旁白', c: '其实做水果饭很简单，先把米饭做好，然后再把一块块新鲜的水果放进去，水果饭就做好了。', p: 'Qíshí zuò shuǐguǒ fàn hěn jiǎndān, xiān bǎ mǐfàn zuòhǎo, ránhòu zài bǎ yí kuàikuài xīnxiān de shuǐguǒ fàng jìnqu, shuǐguǒ fàn jiù zuòhǎo le.', en: 'Fruit rice is easy to make: prepare the rice first, then add pieces of fresh fruit, and it is ready.' },
          { s: 'N', speaker: '旁白', c: '你可以做苹果饭、香蕉饭，要是你愿意，还可以做西瓜饭。', p: 'Nǐ kěyǐ zuò píngguǒ fàn, xiāngjiāo fàn, yàoshi nǐ yuànyì, hái kěyǐ zuò xīguā fàn.', en: 'You can make apple rice or banana rice, and if you like, watermelon rice as well.' },
          { s: 'N', speaker: '旁白', c: '多吃新鲜水果对身体好。', p: 'Duō chī xīnxiān shuǐguǒ duì shēntǐ hǎo.', en: 'Eating plenty of fresh fruit is good for your health.' },
        ],
      },
    ],
    vocab: [
      { c: '打扫', p: 'dǎsǎo', pos: 'v.', en: 'to clean; to sweep' },
      { c: '干净', p: 'gānjìng', pos: 'adj.', en: 'clean' },
      { c: '然后', p: 'ránhòu', pos: 'conj.', en: 'then; after that' },
      { c: '冰箱', p: 'bīngxiāng', pos: 'n.', en: 'refrigerator' },
      { c: '洗澡', p: 'xǐ zǎo', pos: 'v.', en: 'to take a bath or shower' },
      { c: '节目', p: 'jiémù', pos: 'n.', en: 'programme' },
      { c: '月亮', p: 'yuèliang', pos: 'n.', en: 'moon' },
      { c: '像', p: 'xiàng', pos: 'v.', en: 'to be like' },
      { c: '盘子', p: 'pánzi', pos: 'n.', en: 'plate' },
      { c: '刮风', p: 'guā fēng', pos: 'v.', en: 'to be windy' },
      { c: '叔叔', p: 'shūshu', pos: 'n.', en: 'uncle' },
      { c: '阿姨', p: 'āyí', pos: 'n.', en: 'aunt' },
      { c: '故事', p: 'gùshi', pos: 'n.', en: 'story' },
      { c: '声音', p: 'shēngyīn', pos: 'n.', en: 'sound; voice' },
      { c: '菜单', p: 'càidān', pos: 'n.', en: 'menu' },
      { c: '简单', p: 'jiǎndān', pos: 'adj.', en: 'simple' },
      { c: '香蕉', p: 'xiāngjiāo', pos: 'n.', en: 'banana' },
    ],
    notes: [
      {
        title: '“把”字句3：A把B+V+结果补语/趋向补语 · The Ba-Sentence 3: A把B + V + Complement of Result/Direction',
        summary: 'Use A把B + V + a resultative or directional complement when an action produces a result for a definite object or changes its position.',
        examples: [
          { c: '我把衣服洗干净了。', p: 'Wǒ bǎ yīfu xǐ gānjìng le.', en: 'I washed the clothes clean.' },
          { c: '请同学们把铅笔拿出来。', p: 'Qǐng tóngxuémen bǎ qiānbǐ ná chūlai.', en: 'Students, please take out your pencils.' },
          { c: '你把水果拿过来。', p: 'Nǐ bǎ shuǐguǒ ná guòlai.', en: 'Bring the fruit over here.' },
        ],
      },
      {
        title: '先……，再/又……，然后…… · The Structure “先……，再/又……，然后……”',
        summary: '先, 再/又, and 然后 mark the order of actions. 再 introduces an action not yet completed; 又 introduces one that has already occurred.',
        examples: [
          { c: '回家以后，我先做作业，然后吃饭。', p: 'Huí jiā yǐhòu, wǒ xiān zuò zuòyè, ránhòu chīfàn.', en: 'After going home, I do my homework first and then eat.' },
          { c: '你先把电视节目看完吧，然后再给我回电话。', p: 'Nǐ xiān bǎ diànshì jiémù kànwán ba, ránhòu zài gěi wǒ huí diànhuà.', en: 'Finish the television programme first, then call me back.' },
          { c: '我先坐了一个小时公共汽车，又坐了一会儿地铁才到小刚家。', p: 'Wǒ xiān zuò le yí ge xiǎoshí gōnggòng qìchē, yòu zuò le yíhuìr dìtiě cái dào Xiǎogāng jiā.', en: "I first took a bus for an hour, then the subway for a while before reaching Xiaogang's home." },
        ],
      },
    ],
  },
  {
    no: 15,
    bookPage: 125,
    pdfPage: 141,
    han: '其他都没什么问题',
    pinyin: 'Qítā dōu méi shénme wèntí',
    en: 'The rest of them are all OK',
    focus: '除了……以外，都/还/也…… · 疑问代词活用2 · 程度的表达：极了',
    texts: [
      {
        title: '在办公室 · In the office',
        lines: [
          { s: 'A', speaker: '大山', c: '老师，我来中国留学两年了，但是我的汉语水平提高得一点儿也不快啊。', p: 'Lǎoshī, wǒ lái Zhōngguó liú xué liǎng nián le, dànshi wǒ de Hànyǔ shuǐpíng tí gāo de yìdiǎnr yě bù kuài a.', en: 'Teacher, I have studied in China for two years, but my Chinese is not improving quickly at all.' },
          { s: 'B', speaker: '老师', c: '你每天认真学习，做练习，完成作业，一直不错啊。', p: 'Nǐ měi tiān rènzhēn xuéxí, zuò liànxí, wán chéng zuòyè, yìzhí búcuò a.', en: 'You study seriously, do the exercises, and complete your homework every day. You have been doing well.' },
          { s: 'A', speaker: '大山', c: '这是我昨天的作业，您帮我看看对不对。', p: 'Zhè shì wǒ zuótiān de zuòyè, nín bāng wǒ kànkan duì bu duì.', en: 'This is my homework from yesterday. Please check whether it is correct.' },
          { s: 'B', speaker: '老师', c: '写得不错，除了这个句子意思有些不清楚外，其他都没什么问题。', p: 'Xiě de búcuò, chúle zhège jùzi yìsi yǒuxiē bù qīngchu wài, qítā dōu méi shénme wèntí.', en: 'It is well written. Apart from this sentence being a little unclear, everything else is fine.' },
          { s: 'A', speaker: '大山', c: '谢谢老师！', p: 'Xièxie lǎoshī!', en: 'Thank you, teacher!' },
          { s: 'B', speaker: '老师', c: '以后有什么不明白的地方，可以给我打电话或者发电子邮件。', p: 'Yǐhòu yǒu shénme bù míngbai de dìfang, kěyǐ gěi wǒ dǎ diànhuà huòzhě fā diànzǐ yóujiàn.', en: "If there is anything you don't understand in future, you can call or email me." },
        ],
      },
      {
        title: '在教室 · In the classroom',
        lines: [
          { s: 'A', speaker: '学生', c: '老师，除了小云，其他人都来了。', p: 'Lǎoshī, chúle Xiǎoyún, qítā rén dōu lái le.', en: 'Teacher, everyone except Xiaoyun is here.' },
          { s: 'B', speaker: '老师', c: '比赛马上就要开始了，小云怎么还没来？', p: 'Bǐsài mǎshàng jiù yào kāishǐ le, Xiǎoyún zěnme hái méi lái?', en: "The competition is about to begin. Why hasn't Xiaoyun arrived?" },
          { s: 'A', speaker: '学生', c: '刚才给她打电话了，她在路上呢。', p: 'Gāngcái gěi tā dǎ diànhuà le, tā zài lùshang ne.', en: 'I called her just now. She is on the way.' },
          { s: 'B', speaker: '老师', c: '不等她了，我先给大家讲讲这次比赛的要求和一些需要注意的地方。', p: 'Bù děng tā le, wǒ xiān gěi dàjiā jiǎngjiang zhè cì bǐsài de yāoqiú hé yìxiē xūyào zhù yì de dìfang.', en: 'We will not wait. I will first explain the requirements and points to note for this competition.' },
          { s: 'A', speaker: '学生', c: '老师，您放心，今天的比赛我们一定能拿第一。', p: 'Lǎoshī, nín fàngxīn, jīntiān de bǐsài wǒmen yídìng néng ná dì yī.', en: "Teacher, don't worry. We can definitely take first place today." },
        ],
      },
      {
        title: '在休息室 · In the lounge',
        lines: [
          { s: 'A', speaker: '同事', c: '现在用电脑上网真方便啊！', p: 'Xiànzài yòng diànnǎo shàng wǎng zhēn fāngbiàn a!', en: 'Using a computer to go online is so convenient now!' },
          { s: 'B', speaker: '小刚', c: '是啊，除了看新闻，人们还可以在网上听歌、看电影、买东西。', p: 'Shì a, chúle kàn xīnwén, rénmen hái kěyǐ zài wǎngshang tīng gē, kàn diànyǐng, mǎi dōngxi.', en: 'Yes. Besides reading the news, people can listen to music, watch films, and shop online.' },
          { s: 'A', speaker: '同事', c: '对了，你从网上买的那件衣服呢？怎么没见你穿？', p: 'Duìle, nǐ cóng wǎngshang mǎi de nà jiàn yīfu ne? Zěnme méi jiàn nǐ chuān?', en: 'By the way, what about the clothes you bought online? Why have I not seen you wear them?' },
          { s: 'B', speaker: '小刚', c: '那件衣服我穿着有点儿小，给我弟弟了。', p: 'Nà jiàn yīfu wǒ chuānzhe yǒudiǎnr xiǎo, gěi wǒ dìdi le.', en: 'Those clothes were a little small on me, so I gave them to my younger brother.' },
          { s: 'A', speaker: '同事', c: '他满意吗？', p: 'Tā mǎnyì ma?', en: 'Was he satisfied?' },
          { s: 'B', speaker: '小刚', c: '不用花钱，还有新衣服穿，他满意极了。', p: 'Búyòng huā qián, hái yǒu xīn yīfu chuān, tā mǎnyì jí le.', en: 'He did not have to spend any money and got new clothes to wear. He was delighted.' },
        ],
      },
      {
        title: '课文 15-4 · Text 15-4',
        lines: [
          { s: 'N', speaker: '旁白', c: '除了春节、中秋节以外，啤酒节也是这里很重要的一个节日。', p: 'Chúle Chūnjié, Zhōngqiū Jié yǐwài, píjiǔ jié yě shì zhèli hěn zhòngyào de yí ge jiérì.', en: 'Besides Spring Festival and Mid-Autumn Festival, the beer festival is also an important local holiday.' },
          { s: 'N', speaker: '旁白', c: '这个地方每年夏天都要举行一次啤酒节。', p: 'Zhège dìfang měi nián xiàtiān dōu yào jǔxíng yí cì píjiǔ jié.', en: 'This place holds a beer festival every summer.' },
          { s: 'N', speaker: '旁白', c: '在啤酒节上，你可以喝到世界上不同地方的啤酒。', p: 'Zài píjiǔ jié shang, nǐ kěyǐ hēdào shìjiè shang bùtóng dìfang de píjiǔ.', en: 'At the festival, you can drink beer from different parts of the world.' },
          { s: 'N', speaker: '旁白', c: '除了喝啤酒，你还可以在街道两边看到世界上不同地方的歌舞。', p: 'Chúle hē píjiǔ, nǐ hái kěyǐ zài jiēdào liǎngbiān kàndào shìjiè shang bùtóng dìfang de gēwǔ.', en: 'Besides drinking beer, you can see songs and dances from around the world along both sides of the street.' },
          { s: 'N', speaker: '旁白', c: '你想不想了解世界各个地方的啤酒文化？', p: 'Nǐ xiǎng bu xiǎng liǎojiě shìjiè gège dìfang de píjiǔ wénhuà?', en: 'Would you like to learn about beer culture around the world?' },
          { s: 'N', speaker: '旁白', c: '来这里的啤酒节看看吧。', p: 'Lái zhèli de píjiǔ jié kànkan ba.', en: 'Come and take a look at the beer festival here.' },
        ],
      },
    ],
    vocab: [
      { c: '留学', p: 'liú xué', pos: 'v.', en: 'to study abroad' },
      { c: '水平', p: 'shuǐpíng', pos: 'n.', en: 'level; standard' },
      { c: '提高', p: 'tí gāo', pos: 'v.', en: 'to improve' },
      { c: '练习', p: 'liànxí', pos: 'n.', en: 'exercise' },
      { c: '完成', p: 'wán chéng', pos: 'v.', en: 'to complete' },
      { c: '句子', p: 'jùzi', pos: 'n.', en: 'sentence' },
      { c: '其他', p: 'qítā', pos: 'pron.', en: 'the rest' },
      { c: '发', p: 'fā', pos: 'v.', en: 'to send' },
      { c: '要求', p: 'yāoqiú', pos: 'n.', en: 'requirement' },
      { c: '注意', p: 'zhù yì', pos: 'v.', en: 'to pay attention to' },
      { c: '上网', p: 'shàng wǎng', pos: 'v.', en: 'to surf the Internet' },
      { c: '除了', p: 'chúle', pos: 'prep.', en: 'other than; besides' },
      { c: '新闻', p: 'xīnwén', pos: 'n.', en: 'news' },
      { c: '花', p: 'huā', pos: 'v.', en: 'to spend' },
      { c: '极（了）', p: 'jí (le)', pos: 'adv.', en: 'extremely' },
      { c: '节日', p: 'jiérì', pos: 'n.', en: 'festival' },
      { c: '举行', p: 'jǔxíng', pos: 'v.', en: 'to hold an event', supplementary: true },
      { c: '世界', p: 'shìjiè', pos: 'n.', en: 'world' },
      { c: '街道', p: 'jiēdào', pos: 'n.', en: 'street' },
      { c: '各', p: 'gè', pos: 'pron.', en: 'each', supplementary: true },
      { c: '文化', p: 'wénhuà', pos: 'n.', en: 'culture' },
    ],
    notes: [
      {
        title: '除了……以外，都/还/也…… · The Structure “除了……以外，都/还/也……”',
        summary: '除了……以外，都…… means “all except …”. With 还 or 也, it means “besides …, also …”. 以外 may be omitted.',
        examples: [
          { c: '除了这个汉字以外，别的汉字我都认识。', p: 'Chúle zhège Hànzì yǐwài, bié de Hànzì wǒ dōu rènshi.', en: 'I know every Chinese character except this one.' },
          { c: '除了汉语以外，我还会说英语。', p: 'Chúle Hànyǔ yǐwài, wǒ hái huì shuō Yīngyǔ.', en: 'Besides Chinese, I can also speak English.' },
          { c: '除了小云，其他人都来了。', p: 'Chúle Xiǎoyún, qítā rén dōu lái le.', en: 'Everyone except Xiaoyun came.' },
        ],
      },
      {
        title: '疑问代词活用2 · Flexible Use of Interrogative Pronouns 2',
        summary: '什么 can act as an indefinite demonstrative pronoun, replacing an unspecified person or thing and making the tone more polite. Omitting it does not change the core meaning.',
        examples: [
          { c: '这个饭馆有没有什么特别好吃的菜？', p: 'Zhège fànguǎn yǒu méiyǒu shénme tèbié hǎochī de cài?', en: 'Does this restaurant have any especially tasty dishes?' },
          { c: '周末你有没有什么打算？', p: 'Zhōumò nǐ yǒu méiyǒu shénme dǎsuàn?', en: 'Do you have any plans for the weekend?' },
          { c: '以后有什么不明白的地方，可以给我打电话或者发电子邮件。', p: 'Yǐhòu yǒu shénme bù míngbai de dìfang, kěyǐ gěi wǒ dǎ diànhuà huòzhě fā diànzǐ yóujiàn.', en: "If there is anything you don't understand later, you can call or email me." },
        ],
      },
      {
        title: '程度的表达：极了 · “极了” Used to Indicate Degree',
        summary: 'An adjective or mental verb followed by 极了 expresses the highest or an extreme degree.',
        examples: [
          { c: '我的小狗可爱极了。', p: 'Wǒ de xiǎogǒu kě’ài jí le.', en: 'My puppy is extremely cute.' },
          { c: '今天天气冷极了。', p: 'Jīntiān tiānqì lěng jí le.', en: 'The weather is extremely cold today.' },
          { c: '他满意极了。', p: 'Tā mǎnyì jí le.', en: 'He was extremely satisfied.' },
        ],
      },
    ],
  },
]
