// Source-aligned lesson data transcribed from HSK Standard Course 3.
// PDF pages used for this module: 62-105 (printed pages 46-86).

export const HSK3_LESSONS_06_10 = [
  {
    no: 6,
    han: '怎么突然找不到了',
    pinyin: 'Zěnme tūrán zhǎo bu dào le',
    en: 'Why are they suddenly missing',
    focus: '可能补语：V得/不 + Complement · N + 呢 询问处所 · 刚 vs 刚才',
    texts: [
      {
        title: 'Text 1 · 在客厅  In the living room',
        lines: [
          { s: 'A', c: '我的眼镜呢？怎么突然找不到了？你看见了吗？', p: 'Wǒ de yǎnjing ne? Zěnme tūrán zhǎo bu dào le? Nǐ kànjiàn le ma?', en: 'Where are my glasses? Why have they suddenly gone missing? Have you seen them?' },
          { s: 'B', c: '我没看见啊。', p: 'Wǒ méi kànjiàn a.', en: "I haven't seen them." },
          { s: 'A', c: '我离不开眼镜，没有眼镜，我一个字也看不清楚。', p: 'Wǒ líbukāi yǎnjing, méiyǒu yǎnjing, wǒ yí ge zì yě kàn bu qīngchu.', en: "I can't manage without my glasses. Without them, I can't see a single character clearly." },
          { s: 'B', c: '你去房间找找，是不是刚才放在桌子上了？', p: 'Nǐ qù fángjiān zhǎozhao, shì bu shì gāngcái fàng zài zhuōzi shàng le?', en: 'Go and look in the room. Did you put them on the table just now?' },
          { s: 'A', c: '我怎么看得到啊？你快过来帮忙啊。', p: 'Wǒ zěnme kàn de dào a? Nǐ kuài guòlai bāng máng a.', en: "How can I see where they are? Come over quickly and help me." },
          { s: 'B', c: '好吧，我帮你去找找。', p: 'Hǎo ba, wǒ bāng nǐ qù zhǎozhao.', en: "All right, I'll help you look for them." },
        ],
      },
      {
        title: 'Text 2 · 在打电话  On the phone',
        lines: [
          { s: 'A', c: '今天的作业你做完了吗？', p: 'Jīntiān de zuòyè nǐ zuòwán le ma?', en: "Have you finished today's homework?" },
          { s: 'B', c: '刚做完，你呢？', p: 'Gāng zuòwán, nǐ ne?', en: 'I just finished it. What about you?' },
          { s: 'A', c: '今天这些题特别难，我看不懂，不会做，你能帮我吗？', p: 'Jīntiān zhèxiē tí tèbié nán, wǒ kàn bu dǒng, bú huì zuò, nǐ néng bāng wǒ ma?', en: "Today's questions are especially difficult. I don't understand them and don't know how to do them. Can you help me?" },
          { s: 'B', c: '电话里讲不明白，你来我家吧，我给你讲讲。', p: 'Diànhuà lǐ jiǎng bu míngbai, nǐ lái wǒ jiā ba, wǒ gěi nǐ jiǎngjiang.', en: "I can't explain them clearly over the phone. Come to my house and I'll explain them to you." },
          { s: 'A', c: '好啊，我锻炼完了就过去。', p: 'Hǎo a, wǒ duànliàn wán le jiù guòqu.', en: "Okay. I'll come over after I finish exercising." },
        ],
      },
      {
        title: 'Text 3 · 在休息室  In the lounge',
        lines: [
          { s: 'A', c: '你怎么有点儿不高兴？', p: 'Nǐ zěnme yǒudiǎnr bù gāoxìng?', en: 'Why do you seem a little unhappy?' },
          { s: 'B', c: '我想请小丽吃饭，但是找不到好饭馆。', p: 'Wǒ xiǎng qǐng Xiǎolì chī fàn, dànshì zhǎo bu dào hǎo fànguǎn.', en: "I want to invite Xiaoli to dinner, but I can't find a good restaurant." },
          { s: 'A', c: '那你请她听音乐会吧，她喜欢听音乐。', p: 'Nà nǐ qǐng tā tīng yīnyuèhuì ba, tā xǐhuan tīng yīnyuè.', en: 'Then invite her to a concert. She likes listening to music.' },
          { s: 'B', c: '音乐会人太多，买不到票。', p: 'Yīnyuèhuì rén tài duō, mǎi bu dào piào.', en: "There are too many people at concerts, and I can't get tickets." },
          { s: 'A', c: '那去公园走走，聊聊天儿吧。', p: 'Nà qù gōngyuán zǒuzou, liáoliao tiānr ba.', en: 'Then go for a walk in the park and have a chat.' },
          { s: 'B', c: '公园太大，多累啊。', p: 'Gōngyuán tài dà, duō lèi a.', en: 'The park is too big. That would be exhausting!' },
        ],
      },
      {
        title: 'Text 4 · 在客厅  In the living room',
        lines: [
          { s: 'A', c: '你怎么还喝咖啡？', p: 'Nǐ zěnme hái hē kāfēi?', en: 'Why are you still drinking coffee?' },
          { s: 'B', c: '怎么了？', p: 'Zěnme le?', en: "What's wrong?" },
          { s: 'A', c: '你不是说晚上睡不着觉吗？', p: 'Nǐ bú shì shuō wǎnshang shuì bu zháo jiào ma?', en: "Didn't you say you couldn't fall asleep at night?" },
          { s: 'B', c: '没事，我只喝一杯。', p: 'Méi shì, wǒ zhǐ hē yì bēi.', en: "It's fine. I'll only drink one cup." },
          { s: 'A', c: '你还是喝杯牛奶吧，可以睡得更好些。', p: 'Nǐ háishi hē bēi niúnǎi ba, kěyǐ shuì de gèng hǎo xiē.', en: "You'd better drink a glass of milk; then you can sleep better." },
          { s: 'B', c: '好吧，牛奶呢？', p: 'Hǎo ba, niúnǎi ne?', en: 'All right. Where is the milk?' },
          { s: 'A', c: '还没买呢。', p: 'Hái méi mǎi ne.', en: "I haven't bought any yet." },
        ],
      },
    ],
    vocab: [
      { c: '眼镜', p: 'yǎnjing', pos: 'n.', en: 'glasses, spectacles', supplementary: true },
      { c: '突然', p: 'tūrán', pos: 'adv.', en: 'suddenly' },
      { c: '离开', p: 'lí kāi', pos: 'v.', en: 'to leave, to part with' },
      { c: '清楚', p: 'qīngchu', pos: 'adj.', en: 'clear, distinct' },
      { c: '刚才', p: 'gāngcái', pos: 'n.', en: 'just now' },
      { c: '帮忙', p: 'bāng máng', pos: 'v.', en: 'to help' },
      { c: '特别', p: 'tèbié', pos: 'adv.', en: 'extraordinarily' },
      { c: '讲', p: 'jiǎng', pos: 'v.', en: 'to explain' },
      { c: '明白', p: 'míngbai', pos: 'adj.', en: 'clear' },
      { c: '锻炼', p: 'duànliàn', pos: 'v.', en: 'to do physical exercise' },
      { c: '音乐', p: 'yīnyuè', pos: 'n.', en: 'music' },
      { c: '公园', p: 'gōngyuán', pos: 'n.', en: 'park' },
      { c: '聊天（儿）', p: 'liáo tiān (r)', pos: 'v.', en: 'to chat' },
      { c: '睡着', p: 'shuì zháo', pos: 'v.', en: 'to fall asleep', supplementary: true },
      { c: '更', p: 'gèng', pos: 'adv.', en: 'more, even more' },
    ],
    notes: [
      {
        title: '可能补语：V得/不 + Complements of Possibility · Complements of Possibility Introduced by “V得/不”',
        summary: '“V得 + complement” and “V不 + complement” indicate whether a result can be obtained or a goal reached. 得 marks the positive form and 不 the negative; the complement is usually a result or directional complement, an adjective, or a verb. Questions use “V得 + complement V不 + complement” or “V得 + complement 吗”.',
        examples: [
          { c: '我看得清楚那个汉字。', p: 'Wǒ kàn de qīngchu nàge Hànzì.', en: 'I can see that Chinese character clearly.' },
          { c: '楼太高了，我上不去。', p: 'Lóu tài gāo le, wǒ shàng bu qù.', en: 'The building is too tall; I cannot get up there.' },
          { c: '老师说的话你听得见听不见？', p: 'Lǎoshī shuō de huà nǐ tīng de jiàn tīng bu jiàn?', en: 'Can you hear what the teacher is saying?' },
          { c: '我找不到好饭馆。', p: 'Wǒ zhǎo bu dào hǎo fànguǎn.', en: 'I cannot find a good restaurant.' },
          { c: '买到', p: 'mǎi dào', en: 'to manage to buy or get something' },
          { c: '买完', p: 'mǎi wán', en: 'to finish shopping or buy everything needed' },
          { c: '买得到', p: 'mǎi de dào', en: 'can buy; be able to purchase' },
          { c: '买不到', p: 'mǎi bu dào', en: 'cannot buy; fail to purchase' },
          { c: '买得完', p: 'mǎi de wán', en: 'can buy everything or finish shopping' },
          { c: '买不完', p: 'mǎi bu wán', en: 'cannot finish shopping or buy everything' },
          { c: '看见', p: 'kàn jiàn', en: 'to see; catch sight of' },
          { c: '看清楚', p: 'kàn qīngchu', en: 'to see clearly; get a clear view' },
          { c: '看明白', p: 'kàn míngbai', en: 'to understand after reading or watching' },
          { c: '看到', p: 'kàn dào', en: 'to catch sight of; spot' },
          { c: '看得见', p: 'kàn de jiàn', en: 'can see; be visible' },
          { c: '看不见', p: 'kàn bu jiàn', en: 'cannot see; be invisible' },
          { c: '看得清楚', p: 'kàn de qīngchu', en: 'can see clearly' },
          { c: '看不清楚', p: 'kàn bu qīngchu', en: 'cannot see clearly' },
          { c: '看得明白', p: 'kàn de míngbai', en: 'can understand by watching or reading' },
          { c: '看不明白', p: 'kàn bu míngbai', en: 'cannot understand by watching or reading' },
          { c: '看得到', p: 'kàn de dào', en: 'can see; be able to spot' },
          { c: '看不到', p: 'kàn bu dào', en: 'cannot see; fail to spot' },
          { c: '讲清楚', p: 'jiǎng qīngchu', en: 'to explain clearly or speak distinctly' },
          { c: '讲明白', p: 'jiǎng míngbai', en: 'to make something fully understood' },
          { c: '讲到', p: 'jiǎng dào', en: 'to talk about; mention' },
          { c: '讲完', p: 'jiǎng wán', en: 'to finish speaking or telling' },
          { c: '讲得清楚', p: 'jiǎng de qīngchu', en: 'can explain clearly' },
          { c: '讲不清楚', p: 'jiǎng bu qīngchu', en: 'cannot explain clearly' },
          { c: '讲得明白', p: 'jiǎng de míngbai', en: 'can make oneself fully understood' },
          { c: '讲不明白', p: 'jiǎng bu míngbai', en: 'cannot make oneself fully understood' },
          { c: '讲得到', p: 'jiǎng de dào', en: 'can mention or cover a topic' },
          { c: '讲不到', p: 'jiǎng bu dào', en: 'cannot mention or cover a topic' },
          { c: '讲得完', p: 'jiǎng de wán', en: 'can finish speaking' },
          { c: '讲不完', p: 'jiǎng bu wán', en: 'cannot finish speaking' },
          { c: '听清楚', p: 'tīng qīngchu', en: 'to hear clearly' },
          { c: '听明白', p: 'tīng míngbai', en: 'to understand what one hears' },
          { c: '听到', p: 'tīng dào', en: 'to hear a sound or words' },
          { c: '听完', p: 'tīng wán', en: 'to listen all the way through' },
          { c: '听得清楚', p: 'tīng de qīngchu', en: 'can hear clearly' },
          { c: '听不清楚', p: 'tīng bu qīngchu', en: 'cannot hear clearly' },
          { c: '听得明白', p: 'tīng de míngbai', en: 'can understand what is heard' },
          { c: '听不明白', p: 'tīng bu míngbai', en: 'cannot understand what is heard' },
          { c: '听得到', p: 'tīng de dào', en: 'can hear; be able to hear' },
          { c: '听不到', p: 'tīng bu dào', en: 'cannot hear; fail to hear' },
          { c: '听得完', p: 'tīng de wán', en: 'can finish listening' },
          { c: '听不完', p: 'tīng bu wán', en: 'cannot finish listening' },
          { c: '上去', p: 'shàng qù', en: 'to go or climb up' },
          { c: '上完', p: 'shàng wán', en: 'to finish a class or work' },
          { c: '上到', p: 'shàng dào', en: 'to climb up to or reach a high place' },
          { c: '上得去', p: 'shàng de qù', en: 'can go or climb up' },
          { c: '上不去', p: 'shàng bu qù', en: 'cannot go or climb up' },
          { c: '上得完', p: 'shàng de wán', en: 'can finish a class or work' },
          { c: '上不完', p: 'shàng bu wán', en: 'cannot finish a class or work' },
          { c: '上得到', p: 'shàng de dào', en: 'can reach a high place' },
          { c: '上不到', p: 'shàng bu dào', en: 'cannot reach a high place' },
          { c: '做完', p: 'zuò wán', en: 'to finish doing something' },
          { c: '做到', p: 'zuò dào', en: 'to achieve something or keep one’s word' },
          { c: '做明白', p: 'zuò míngbai', en: 'to figure out how to do something' },
          { c: '做清楚', p: 'zuò qīngchu', en: 'to do something neatly and thoroughly' },
          { c: '做得完', p: 'zuò de wán', en: 'can finish doing something' },
          { c: '做不完', p: 'zuò bu wán', en: 'cannot finish doing something' },
          { c: '做得到', p: 'zuò de dào', en: 'can achieve something or keep one’s word' },
          { c: '做不到', p: 'zuò bu dào', en: 'cannot achieve something or keep one’s word' },
          { c: '做得明白', p: 'zuò de míngbai', en: 'can figure out how to do something' },
          { c: '做不明白', p: 'zuò bu míngbai', en: 'cannot figure out how to do something' },
          { c: '做得清楚', p: 'zuò de qīngchu', en: 'can do something thoroughly and neatly' },
          { c: '做不清楚', p: 'zuò bu qīngchu', en: 'cannot do something thoroughly and neatly' },
        ],
      },
      {
        title: '“呢”询问处所：“N+呢” · “N+呢” Used to Ask about Location',
        summary: 'A noun followed by 呢 asks where that person or thing is when the context is clear, such as 妈妈呢？ or 小狗呢？',
        examples: [
          { c: 'A：你的书呢？放在哪儿了？ B：就在桌子上啊。', p: 'A: Nǐ de shū ne? Fàng zài nǎr le? B: Jiù zài zhuōzi shàng a.', en: 'A: Where is your book? Where did you put it? B: It is right on the table.' },
          { c: 'A：我的眼镜呢？你看见了吗？ B：我没看见啊。', p: 'A: Wǒ de yǎnjing ne? Nǐ kànjiàn le ma? B: Wǒ méi kànjiàn a.', en: 'A: Where are my glasses? Have you seen them? B: I have not seen them.' },
        ],
      },
      {
        title: '“刚”和“刚才” · Comparison of “刚” and “刚才”',
        summary: 'Both refer to a recent action. 刚 is an adverb immediately before a verb and means a short time from the speaker’s perspective, which may be minutes, days, or even months. 刚才 is a time noun, usually only several minutes ago, and may appear before the verb or at the beginning of the sentence.',
        examples: [
          { c: '爸爸刚出去。', p: 'Bàba gāng chūqu.', en: 'Dad has just gone out.' },
          { c: '我刚喝完一杯咖啡。', p: 'Wǒ gāng hēwán yì bēi kāfēi.', en: 'I have just finished a cup of coffee.' },
          { c: '我刚放在桌子上，现在就没了。', p: 'Wǒ gāng fàng zài zhuōzi shàng, xiànzài jiù méi le.', en: 'I just put it on the table, and now it is gone.' },
          { c: '儿子刚做完作业。', p: 'Érzi gāng zuòwán zuòyè.', en: 'The son has just finished his homework.' },
          { c: '爸爸刚才出去了。', p: 'Bàba gāngcái chūqu le.', en: 'Dad went out just now.' },
          { c: '刚才我喝了一杯咖啡。', p: 'Gāngcái wǒ hē le yì bēi kāfēi.', en: 'I drank a cup of coffee just now.' },
          { c: '眼镜周明刚才放在桌子上了。', p: 'Yǎnjing Zhōu Míng gāngcái fàng zài zhuōzi shàng le.', en: 'Zhou Ming put the glasses on the table just now.' },
          { c: '刚才儿子在做作业。', p: 'Gāngcái érzi zài zuò zuòyè.', en: 'The son was doing his homework just now.' },
        ],
      },
    ],
  },
  {
    no: 7,
    han: '我跟她都认识五年了',
    pinyin: 'Wǒ gēn tā dōu rènshi wǔ nián le',
    en: "I've known her for five years",
    focus: '时段的表达 · 对……感兴趣 · 用“半”“刻”“差”表示时间',
    texts: [
      {
        title: 'Text 1 · 在办公室  In the office',
        lines: [
          { s: 'A', c: '那个漂亮的新同事是谁？', p: 'Nàge piàoliang de xīn tóngshi shì shéi?', en: 'Who is that pretty new colleague?' },
          { s: 'B', c: '那是小丽。', p: 'Nà shì Xiǎolì.', en: 'That is Xiaoli.' },
          { s: 'A', c: '她刚来北京吗？', p: 'Tā gāng lái Běijīng ma?', en: 'Has she just come to Beijing?' },
          { s: 'B', c: '不，她在北京工作三年了。', p: 'Bù, tā zài Běijīng gōngzuò sān nián le.', en: 'No, she has worked in Beijing for three years.' },
          { s: 'A', c: '以前她在哪儿工作？', p: 'Yǐqián tā zài nǎr gōngzuò?', en: 'Where did she work before?' },
          { s: 'B', c: '她在银行工作了两年以后来的我们公司。', p: 'Tā zài yínháng gōngzuò le liǎng nián yǐhòu lái de wǒmen gōngsī.', en: 'She came to our company after working at a bank for two years.' },
        ],
      },
      {
        title: 'Text 2 · 在休息室  In the lounge',
        lines: [
          { s: 'A', c: '周末你跟小丽去哪儿玩儿了？', p: 'Zhōumò nǐ gēn Xiǎolì qù nǎr wánr le?', en: 'Where did you and Xiaoli go for fun at the weekend?' },
          { s: 'B', c: '我们去唱歌了。', p: 'Wǒmen qù chàng gē le.', en: 'We went singing.' },
          { s: 'A', c: '你们唱了多久？', p: 'Nǐmen chàng le duō jiǔ?', en: 'How long did you sing?' },
          { s: 'B', c: '我们唱了两个小时歌，晚上还去听音乐会了。', p: 'Wǒmen chàng le liǎng ge xiǎoshí gē, wǎnshang hái qù tīng yīnyuèhuì le.', en: 'We sang for two hours, and in the evening we also went to a concert.' },
          { s: 'A', c: '你们都对音乐感兴趣吗？', p: 'Nǐmen dōu duì yīnyuè gǎn xìngqù ma?', en: 'Are both of you interested in music?' },
          { s: 'B', c: '她对音乐感兴趣，我对她更感兴趣。', p: 'Tā duì yīnyuè gǎn xìngqù, wǒ duì tā gèng gǎn xìngqù.', en: 'She is interested in music; I am even more interested in her.' },
        ],
      },
      {
        title: 'Text 3 · 在休息室  In the lounge',
        lines: [
          { s: 'A', c: '我跟小丽下个月结婚，到时候欢迎你来。', p: 'Wǒ gēn Xiǎolì xià ge yuè jié hūn, dào shíhou huānyíng nǐ lái.', en: 'Xiaoli and I are getting married next month. You are welcome to come then.' },
          { s: 'B', c: '什么？结婚？', p: 'Shénme? Jié hūn?', en: 'What? Getting married?' },
          { s: 'A', c: '对啊，突然吗？', p: 'Duì a, tūrán ma?', en: 'Yes. Is it sudden?' },
          { s: 'B', c: '你们不是刚认识吗？', p: 'Nǐmen bú shì gāng rènshi ma?', en: "Didn't you just meet?" },
          { s: 'A', c: '我跟她都认识五年了。', p: 'Wǒ gēn tā dōu rènshi wǔ nián le.', en: "I've known her for five years." },
          { s: 'B', c: '你跟她结婚，那我怎么办啊？', p: 'Nǐ gēn tā jié hūn, nà wǒ zěnme bàn a?', en: 'If you marry her, then what am I supposed to do?' },
        ],
      },
      {
        title: 'Text 4 · 在公司门口  At the exit of the office building',
        lines: [
          { s: 'A', c: '你看看手表，怎么迟到了？', p: 'Nǐ kànkan shǒubiǎo, zěnme chídào le?', en: 'Look at your watch. Why are you late?' },
          { s: 'B', c: '没迟到啊。', p: 'Méi chídào a.', en: "I'm not late." },
          { s: 'A', c: '你不是说七点半来接我吗？你迟到了一刻钟。', p: 'Nǐ bú shì shuō qī diǎn bàn lái jiē wǒ ma? Nǐ chídào le yí kè zhōng.', en: "Didn't you say you would pick me up at half past seven? You are fifteen minutes late." },
          { s: 'B', c: '现在不是七点半吗？', p: 'Xiànzài bú shì qī diǎn bàn ma?', en: "Isn't it half past seven now?" },
          { s: 'A', c: '已经差一刻八点了！我都在这儿坐了半个小时了。', p: 'Yǐjīng chà yí kè bā diǎn le! Wǒ dōu zài zhèr zuò le bàn ge xiǎoshí le.', en: "It's already a quarter to eight! I've been sitting here for half an hour." },
          { s: 'B', c: '不是我迟到了，是你的表快了一刻钟。', p: 'Bú shì wǒ chídào le, shì nǐ de biǎo kuài le yí kè zhōng.', en: "I'm not late; your watch is fifteen minutes fast." },
        ],
      },
    ],
    vocab: [
      { c: '同事', p: 'tóngshi', pos: 'n.', en: 'colleague' },
      { c: '以前', p: 'yǐqián', pos: 'n.', en: 'before, ago' },
      { c: '银行', p: 'yínháng', pos: 'n.', en: 'bank' },
      { c: '久', p: 'jiǔ', pos: 'adj.', en: 'for a long time, long' },
      // The source prints no part-of-speech label for this entry.
      { c: '感兴趣', p: 'gǎn xìngqù', pos: '', en: 'to be interested in' },
      { c: '结婚', p: 'jié hūn', pos: 'v.', en: 'to marry, to get married' },
      { c: '欢迎', p: 'huānyíng', pos: 'v.', en: 'to welcome' },
      { c: '迟到', p: 'chídào', pos: 'v.', en: 'to be late' },
      { c: '半', p: 'bàn', pos: 'num.', en: 'half' },
      { c: '接', p: 'jiē', pos: 'v.', en: 'to meet (sb.), to pick up (sb.)' },
      { c: '刻', p: 'kè', pos: 'm.', en: 'quarter' },
      { c: '差', p: 'chà', pos: 'v.', en: 'to fall short of' },
    ],
    notes: [
      {
        title: '时段的表达 · To Express a Period of Time',
        summary: 'A duration complement indicates how long an action or state lasts. “S + V + 了 + duration + O” gives the duration of an action. Adding a final 了 - “S + V + 了 + duration + O + 了” - shows that the action is still continuing.',
        examples: [
          { c: '她工作了三年。', p: 'Tā gōngzuò le sān nián.', en: 'She worked for three years.' },
          { c: '我们坐了一个小时公共汽车。', p: 'Wǒmen zuò le yí ge xiǎoshí gōnggòng qìchē.', en: 'We rode the bus for one hour.' },
          { c: '你怎么晚到了一刻钟？', p: 'Nǐ zěnme wǎn dào le yí kè zhōng?', en: 'Why did you arrive fifteen minutes late?' },
          { c: '我们唱了两个小时歌。', p: 'Wǒmen chàng le liǎng ge xiǎoshí gē.', en: 'We sang for two hours.' },
          { c: '我学习了一年汉语了。', p: 'Wǒ xuéxí le yì nián Hànyǔ le.', en: 'I have been studying Chinese for a year.' },
          { c: '她看了半个小时电视了。', p: 'Tā kàn le bàn ge xiǎoshí diànshì le.', en: 'She has been watching television for half an hour.' },
          { c: '他们游了二十分钟泳了。', p: 'Tāmen yóu le èrshí fēnzhōng yǒng le.', en: 'They have been swimming for twenty minutes.' },
          { c: '我都在这儿坐了半个小时了。', p: 'Wǒ dōu zài zhèr zuò le bàn ge xiǎoshí le.', en: 'I have been sitting here for half an hour.' },
        ],
      },
      {
        title: '表达兴趣 · To Express an Interest',
        summary: '“对……感兴趣” and “对……有兴趣” express interest in something. Their negative forms are “对……不感兴趣” and “对……没（有）兴趣”. A degree adverb precedes 感兴趣 or 有兴趣.',
        examples: [
          { c: '他们对电影感兴趣。', p: 'Tāmen duì diànyǐng gǎn xìngqù.', en: 'They are interested in films.' },
          { c: '我儿子对打篮球不感兴趣。', p: 'Wǒ érzi duì dǎ lánqiú bù gǎn xìngqù.', en: 'My son is not interested in playing basketball.' },
          { c: '同学们对汉语有兴趣。你们都对音乐感兴趣吗？', p: 'Tóngxuémen duì Hànyǔ yǒu xìngqù. Nǐmen dōu duì yīnyuè gǎn xìngqù ma?', en: 'The students are interested in Chinese. Are you all interested in music?' },
          { c: '我对她更感兴趣。', p: 'Wǒ duì tā gèng gǎn xìngqù.', en: 'I am even more interested in her.' },
        ],
      },
      {
        title: '用“半”“刻”“差”表示时间 · To Indicate Time Using “半” “刻” or “差”',
        summary: '半 means half past the hour; 刻 means a quarter of an hour; and 差 introduces the time remaining until the next hour. 一刻钟 is a duration of fifteen minutes.',
        examples: [
          { c: '一点半', p: 'yì diǎn bàn', en: 'half past one' },
          { c: '十二点一刻', p: 'shí’èr diǎn yí kè', en: 'a quarter past twelve' },
          { c: '十二点三刻 / 差一刻一点', p: 'shí’èr diǎn sān kè / chà yí kè yì diǎn', en: 'a quarter to one' },
          { c: '差五分十二点', p: 'chà wǔ fēn shí’èr diǎn', en: 'five minutes to twelve' },
          { c: '我等了你一刻钟。', p: 'Wǒ děng le nǐ yí kè zhōng.', en: 'I waited for you for fifteen minutes.' },
        ],
      },
    ],
  },
  {
    no: 8,
    han: '你去哪儿我就去哪儿',
    pinyin: 'Nǐ qù nǎr wǒ jiù qù nǎr',
    en: "I'll go wherever you go",
    focus: '“又”和“再” · 疑问代词活用1',
    texts: [
      {
        title: 'Text 1 · 在休息室  In the lounge',
        lines: [
          { s: 'A', c: '听说你最近打算买房子？', p: 'Tīngshuō nǐ zuìjìn dǎsuan mǎi fángzi?', en: "I hear you've recently been planning to buy a home?" },
          { s: 'B', c: '是，昨天去看了看，今天又去看了看，明天还要再去看看。', p: 'Shì, zuótiān qù kàn le kan, jīntiān yòu qù kàn le kan, míngtiān hái yào zài qù kànkan.', en: 'Yes. I looked at some yesterday, looked at more today, and will go look again tomorrow.' },
          { s: 'A', c: '都不满意吗？', p: 'Dōu bù mǎnyì ma?', en: 'Are you dissatisfied with all of them?' },
          { s: 'B', c: '一个没有电梯，不方便。一个有电梯，但是在二十层。', p: 'Yí ge méiyǒu diàntī, bù fāngbiàn. Yí ge yǒu diàntī, dànshì zài èrshí céng.', en: 'One has no elevator, which is inconvenient. Another has an elevator, but it is on the twentieth floor.' },
          { s: 'A', c: '二十层怎么了？', p: 'Èrshí céng zěnme le?', en: "What's wrong with the twentieth floor?" },
          { s: 'B', c: '太高了，往下看多害怕啊！', p: 'Tài gāo le, wǎng xià kàn duō hàipà a!', en: "It's too high. Looking down from there would be frightening!" },
        ],
      },
      {
        title: 'Text 2 · 在学校  At school',
        lines: [
          { s: 'A', c: '听说你下个星期就要回国了？', p: 'Tīngshuō nǐ xià ge xīngqī jiù yào huí guó le?', en: 'I hear you are going back to your country next week?' },
          { s: 'B', c: '是啊，真不想离开北京。', p: 'Shì a, zhēn bù xiǎng líkāi Běijīng.', en: "Yes. I really don't want to leave Beijing." },
          { s: 'A', c: '我下星期不在北京，不能去机场送你了。', p: 'Wǒ xià xīngqī bú zài Běijīng, bù néng qù jīchǎng sòng nǐ le.', en: "I won't be in Beijing next week, so I can't see you off at the airport." },
          { s: 'B', c: '没关系，你忙吧。', p: 'Méi guānxi, nǐ máng ba.', en: "That's all right. Go ahead with what you need to do." },
          { s: 'A', c: '这个小熊猫送给你，欢迎你以后再到中国来。', p: 'Zhège xiǎo xióngmāo sòng gěi nǐ, huānyíng nǐ yǐhòu zài dào Zhōngguó lái.', en: 'This little panda is for you. You are welcome to come to China again.' },
          { s: 'B', c: '谢谢。希望以后能再见面。', p: 'Xièxie. Xīwàng yǐhòu néng zài jiàn miàn.', en: 'Thank you. I hope we can meet again.' },
        ],
      },
      {
        title: 'Text 3 · 在咖啡厅  In a coffee house',
        lines: [
          { s: 'A', c: '小刚，我们坐哪儿？', p: 'Xiǎogāng, wǒmen zuò nǎr?', en: 'Xiaogang, where shall we sit?' },
          { s: 'B', c: '你坐哪儿我就坐哪儿。', p: 'Nǐ zuò nǎr wǒ jiù zuò nǎr.', en: "I'll sit wherever you sit." },
          { s: 'A', c: '坐这儿吧，这儿安静。你想喝什么饮料？', p: 'Zuò zhèr ba, zhèr ānjìng. Nǐ xiǎng hē shénme yǐnliào?', en: 'Sit here; it is quiet here. What would you like to drink?' },
          { s: 'B', c: '你喝什么我就喝什么。', p: 'Nǐ hē shénme wǒ jiù hē shénme.', en: "I'll drink whatever you drink." },
          { s: 'A', c: '喝可乐吧。你等我一会儿，我马上回来。', p: 'Hē kělè ba. Nǐ děng wǒ yíhuìr, wǒ mǎshàng huílai.', en: "Let's have Coke. Wait for me a moment; I'll be right back." },
          { s: 'B', c: '小丽，你去哪儿？你去哪儿我就去哪儿。', p: 'Xiǎolì, nǐ qù nǎr? Nǐ qù nǎr wǒ jiù qù nǎr.', en: "Xiaoli, where are you going? I'll go wherever you go." },
          { s: 'A', c: '我去洗手间。', p: 'Wǒ qù xǐshǒujiān.', en: "I'm going to the restroom." },
        ],
      },
      {
        title: 'Text 4 · 在周明家  At Zhou Ming’s home',
        lines: [
          { s: 'A', c: '快五年了，你几乎没变化。', p: 'Kuài wǔ nián le, nǐ jīhū méi biànhuà.', en: "It's been almost five years, and you have hardly changed." },
          { s: 'B', c: '谁说的？我胖了，以前的衣服都不能穿了。', p: 'Shéi shuō de? Wǒ pàng le, yǐqián de yīfu dōu bù néng chuān le.', en: "Who says? I've put on weight, and I can't wear any of my old clothes." },
          { s: 'A', c: '健康最重要，胖瘦没关系。', p: 'Jiànkāng zuì zhòngyào, pàng shòu méi guānxi.', en: 'Health is most important; being fat or thin does not matter.' },
          { s: 'B', c: '是呀，想吃什么就吃什么。', p: 'Shì ya, xiǎng chī shénme jiù chī shénme.', en: "Exactly. I eat whatever I want." },
          { s: 'A', c: '你做饭还是周明做饭？', p: 'Nǐ zuò fàn háishi Zhōu Míng zuò fàn?', en: 'Do you cook, or does Zhou Ming cook?' },
          { s: 'B', c: '我做，我想吃什么就做什么，想吃多少就做多少。', p: 'Wǒ zuò, wǒ xiǎng chī shénme jiù zuò shénme, xiǎng chī duōshao jiù zuò duōshao.', en: 'I do. I cook whatever I want to eat, and I make as much as I want to eat.' },
        ],
      },
    ],
    vocab: [
      { c: '又', p: 'yòu', pos: 'adv.', en: 'again' },
      { c: '满意', p: 'mǎnyì', pos: 'v.', en: 'to be satisfied' },
      { c: '电梯', p: 'diàntī', pos: 'n.', en: 'elevator' },
      { c: '层', p: 'céng', pos: 'm.', en: 'used for floors' },
      { c: '害怕', p: 'hàipà', pos: 'v.', en: 'to be afraid, to be scared' },
      { c: '熊猫', p: 'xióngmāo', pos: 'n.', en: 'panda' },
      { c: '见面', p: 'jiàn miàn', pos: 'v.', en: 'to meet' },
      { c: '安静', p: 'ānjìng', pos: 'adj.', en: 'quiet' },
      { c: '可乐', p: 'kělè', pos: 'n.', en: 'cola, Coke', supplementary: true },
      { c: '一会儿', p: 'yíhuìr', pos: 'n.', en: 'a moment' },
      { c: '马上', p: 'mǎshàng', pos: 'adv.', en: 'immediately, at once' },
      { c: '洗手间', p: 'xǐshǒujiān', pos: 'n.', en: 'bathroom, restroom' },
      { c: '老', p: 'lǎo', pos: 'adj.', en: 'old' },
      { c: '几乎', p: 'jīhū', pos: 'adv.', en: 'almost' },
      { c: '变化', p: 'biànhuà', pos: 'v.', en: 'to change' },
      { c: '健康', p: 'jiànkāng', pos: 'adj.', en: 'healthy' },
      { c: '重要', p: 'zhòngyào', pos: 'adj.', en: 'important' },
    ],
    notes: [
      {
        title: '“又”和“再” · Comparison of “又” and “再”',
        summary: '又 and 再 both precede a verb to indicate recurrence. “又 + V” normally describes a repeated action or situation that has already occurred, while “再 + V” describes one that has not yet occurred.',
        examples: [
          { c: '上个星期我买了一条裤子，昨天又买了一条。', p: 'Shàng ge xīngqī wǒ mǎi le yì tiáo kùzi, zuótiān yòu mǎi le yì tiáo.', en: 'I bought a pair of trousers last week, and yesterday I bought another pair.' },
          { c: '你上午已经喝了一杯咖啡，下午怎么又喝了一杯？', p: 'Nǐ shàngwǔ yǐjīng hē le yì bēi kāfēi, xiàwǔ zěnme yòu hē le yì bēi?', en: 'You already had a cup of coffee this morning; why did you have another one this afternoon?' },
          { c: '小刚，你前天迟到，昨天迟到，今天怎么又迟到了？', p: 'Xiǎogāng, nǐ qiántiān chídào, zuótiān chídào, jīntiān zěnme yòu chídào le?', en: 'Xiaogang, you were late the day before yesterday and yesterday; why are you late again today?' },
          { c: '我昨天看了一个电影，今天又看了一个。', p: 'Wǒ zuótiān kàn le yí ge diànyǐng, jīntiān yòu kàn le yí ge.', en: 'I watched a film yesterday and watched another one today.' },
          { c: '你只吃了一点儿饭，再吃一点儿吧。', p: 'Nǐ zhǐ chī le yìdiǎnr fàn, zài chī yìdiǎnr ba.', en: 'You ate only a little; have a little more.' },
          { c: '家里只有一个面包了，我们再买一些吧。', p: 'Jiā lǐ zhǐ yǒu yí ge miànbāo le, wǒmen zài mǎi yìxiē ba.', en: 'There is only one loaf of bread left at home; let us buy some more.' },
          { c: '那个饭馆我昨天去了一次，明天还想再去一次。', p: 'Nàge fànguǎn wǒ zuótiān qù le yí cì, míngtiān hái xiǎng zài qù yí cì.', en: 'I went to that restaurant once yesterday and want to go there again tomorrow.' },
          { c: '昨天去看了看，今天又去看了看，明天还要再去看看。', p: 'Zuótiān qù kàn le kan, jīntiān yòu qù kàn le kan, míngtiān hái yào zài qù kànkan.', en: 'I went to look yesterday, looked again today, and will go look again tomorrow.' },
        ],
      },
      {
        title: '疑问代词活用1 · Flexible Use of Interrogative Pronouns 1',
        summary: '就 connects two occurrences of the same interrogative pronoun to indicate an unspecified person, thing, place, or manner. Both pronouns refer to the same thing. If the clauses share a subject, the second subject may be omitted; if they have different subjects, the second subject appears before 就.',
        examples: [
          { c: '什么东西便宜我就买什么。', p: 'Shénme dōngxi piányi wǒ jiù mǎi shénme.', en: 'I buy whatever is inexpensive.' },
          { c: '你哪天有时间就哪天来我家吧。', p: 'Nǐ nǎ tiān yǒu shíjiān jiù nǎ tiān lái wǒ jiā ba.', en: 'Come to my home on whichever day you have time.' },
          { c: '谁喜欢他他就喜欢谁。', p: 'Shéi xǐhuan tā tā jiù xǐhuan shéi.', en: 'He likes whoever likes him.' },
          { c: '你坐哪儿我就坐哪儿。', p: 'Nǐ zuò nǎr wǒ jiù zuò nǎr.', en: 'I will sit wherever you sit.' },
        ],
      },
    ],
  },
  {
    no: 9,
    han: '她的汉语说得跟中国人一样好',
    pinyin: 'Tā de Hànyǔ shuō de gēn Zhōngguórén yíyàng hǎo',
    en: 'She speaks Chinese like a native',
    focus: '越A越B · 比较句1：A跟B一样（+ Adj）',
    texts: [
      {
        title: 'Text 1 · 在教室  In the classroom',
        lines: [
          { s: 'A', c: '马可，你的中文越说越好了！', p: 'Mǎkè, nǐ de Zhōngwén yuè shuō yuè hǎo le!', en: 'Marco, your Chinese is getting better and better!' },
          { s: 'B', c: '哪里哪里，我们班王静说得更好。', p: 'Nǎli nǎli, wǒmen bān Wáng Jìng shuō de gèng hǎo.', en: 'Not at all. Wang Jing in our class speaks even better.' },
          { s: 'A', c: '怎么好？', p: 'Zěnme hǎo?', en: 'How so?' },
          { s: 'B', c: '她的汉语说得跟中国人一样好。', p: 'Tā de Hànyǔ shuō de gēn Zhōngguórén yíyàng hǎo.', en: 'She speaks Chinese as well as a Chinese person.' },
          { s: 'A', c: '王静？我怎么没听说过这个名字？', p: 'Wáng Jìng? Wǒ zěnme méi tīngshuōguo zhège míngzi?', en: "Wang Jing? How come I haven't heard that name?" },
          { s: 'B', c: '她是我们的汉语老师。', p: 'Tā shì wǒmen de Hànyǔ lǎoshī.', en: 'She is our Chinese teacher.' },
        ],
      },
      {
        title: 'Text 2 · 在蛋糕店  In a bakery',
        lines: [
          { s: 'A', c: '别吃了，你已经吃了三块蛋糕了。', p: 'Bié chī le, nǐ yǐjīng chī le sān kuài dàngāo le.', en: 'Stop eating; you have already eaten three pieces of cake.' },
          { s: 'B', c: '这是最后一块。', p: 'Zhè shì zuìhòu yí kuàir.', en: 'This is the last piece.' },
          { s: 'A', c: '你总是吃甜的东西，会越吃越胖。', p: 'Nǐ zǒngshì chī tián de dōngxi, huì yuè chī yuè pàng.', en: 'You are always eating sweet things; the more you eat, the fatter you will get.' },
          { s: 'B', c: '你放心，我一定不会变胖。', p: 'Nǐ fàng xīn, wǒ yídìng bú huì biàn pàng.', en: "Don't worry. I definitely won't get fat." },
          { s: 'A', c: '为什么？', p: 'Wèi shénme?', en: 'Why?' },
          { s: 'B', c: '我们家的人都很瘦，吃不胖。', p: 'Wǒmen jiā de rén dōu hěn shòu, chī bu pàng.', en: 'Everyone in my family is thin; we do not put on weight from eating.' },
        ],
      },
      {
        title: 'Text 3 · 在山上  On the mountain',
        lines: [
          { s: 'A', c: '我有点儿害怕。', p: 'Wǒ yǒudiǎnr hàipà.', en: "I'm a little scared." },
          { s: 'B', c: '怎么了？', p: 'Zěnme le?', en: "What's wrong?" },
          { s: 'A', c: '山越高，路越难走。我也越爬越冷。', p: 'Shān yuè gāo, lù yuè nán zǒu. Wǒ yě yuè pá yuè lěng.', en: 'The higher the mountain, the harder the path. I am also getting colder the higher I climb.' },
          { s: 'B', c: '不用担心，有我呢，我对这儿比较了解。', p: 'Bú yòng dān xīn, yǒu wǒ ne, wǒ duì zhèr bǐjiào liǎojiě.', en: "Don't worry; I'm here, and I know this area fairly well." },
          { s: 'A', c: '那我们先休息一下，一会儿再爬。', p: 'Nà wǒmen xiān xiūxi yíxià, yíhuìr zài pá.', en: "Then let's rest first and climb again in a little while." },
          { s: 'B', c: '好，一会儿我们可以从中间这条路上去。', p: 'Hǎo, yíhuìr wǒmen kěyǐ cóng zhōngjiān zhè tiáo lù shàngqu.', en: 'Okay. In a little while we can go up by this path in the middle.' },
        ],
      },
      {
        title: 'Text 4 · 在小明家  At Xiaoming’s home',
        lines: [
          { s: 'A', c: '小明，你的眼睛怎么跟大熊猫一样了？', p: 'Xiǎomíng, nǐ de yǎnjing zěnme gēn dà xióngmāo yíyàng le?', en: 'Xiaoming, why do your eyes look like a giant panda’s?' },
          { s: 'B', c: '我这几天脚疼，没休息好。', p: 'Wǒ zhè jǐ tiān jiǎo téng, méi xiūxi hǎo.', en: 'My foot has hurt these past few days, and I have not rested well.' },
          { s: 'A', c: '去医院了吗？医生说什么？', p: 'Qù yīyuàn le ma? Yīshēng shuō shénme?', en: 'Did you go to the hospital? What did the doctor say?' },
          { s: 'B', c: '他让我多休息。休息得越多，好得越快。', p: 'Tā ràng wǒ duō xiūxi. Xiūxi de yuè duō, hǎo de yuè kuài.', en: 'He told me to rest more. The more I rest, the faster I will recover.' },
          { s: 'A', c: '下个月的篮球比赛，你能参加吗？', p: 'Xià ge yuè de lánqiú bǐsài, nǐ néng cānjiā ma?', en: 'Can you take part in the basketball match next month?' },
          { s: 'B', c: '一定能参加，一点儿影响也没有。', p: 'Yídìng néng cānjiā, yìdiǎnr yǐngxiǎng yě méiyǒu.', en: 'I can definitely take part; it will not affect me at all.' },
        ],
      },
    ],
    vocab: [
      { c: '中文', p: 'Zhōngwén', pos: 'n.', en: 'Chinese language' },
      { c: '班', p: 'bān', pos: 'n.', en: 'class' },
      { c: '一样', p: 'yíyàng', pos: 'adj.', en: 'same, as…as…' },
      { c: '最后', p: 'zuìhòu', pos: 'n.', en: 'the last one' },
      { c: '放心', p: 'fàng xīn', pos: 'v.', en: "to ease one's mind, to rest assured" },
      { c: '一定', p: 'yídìng', pos: 'adv.', en: 'definitely, certainly' },
      { c: '担心', p: 'dān xīn', pos: 'v.', en: 'to worry' },
      { c: '比较', p: 'bǐjiào', pos: 'adv.', en: 'fairly, rather' },
      { c: '了解', p: 'liǎojiě', pos: 'v.', en: 'to know' },
      { c: '先', p: 'xiān', pos: 'adv.', en: 'first, in advance' },
      { c: '中间', p: 'zhōngjiān', pos: 'n.', en: 'middle' },
      { c: '参加', p: 'cānjiā', pos: 'v.', en: 'to participate' },
      { c: '影响', p: 'yǐngxiǎng', pos: 'n.', en: 'influence' },
    ],
    notes: [
      {
        title: '越A越B · The Structure “越A越B”',
        summary: '“越A越B” means that B changes along with A: the more A changes, the more B changes.',
        examples: [
          { c: '雨越下越大。', p: 'Yǔ yuè xià yuè dà.', en: 'The rain is getting heavier and heavier.' },
          { c: '你的中文越说越好。', p: 'Nǐ de Zhōngwén yuè shuō yuè hǎo.', en: 'The more you speak Chinese, the better it gets.' },
          { c: '越往南，天气越热。', p: 'Yuè wǎng nán, tiānqì yuè rè.', en: 'The farther south one goes, the hotter the weather becomes.' },
          { c: '山越高，路越难走。', p: 'Shān yuè gāo, lù yuè nán zǒu.', en: 'The higher the mountain, the harder the path is to walk.' },
        ],
      },
      {
        title: '比较句1：A跟B一样(+Adj) · Comparative Sentences 1: A跟B一样(+Adj)',
        summary: '“A 跟 B 一样” means A and B are the same after comparison. An adjective may follow to specify the respect being compared. The negative places 不 before 一样.',
        examples: [
          { c: '这本书跟那本书一样。', p: 'Zhè běn shū gēn nà běn shū yíyàng.', en: 'This book is the same as that book.' },
          { c: '儿子跟爸爸一样高。', p: 'Érzi gēn bàba yíyàng gāo.', en: 'The son is as tall as his father.' },
          { c: '这辆车的颜色跟那辆车不一样。', p: 'Zhè liàng chē de yánsè gēn nà liàng chē bù yíyàng.', en: "This car's colour is different from that car's." },
          { c: '她的汉语说得跟中国人一样好。', p: 'Tā de Hànyǔ shuō de gēn Zhōngguórén yíyàng hǎo.', en: 'She speaks Chinese as well as a Chinese person.' },
        ],
      },
    ],
  },
  {
    no: 10,
    han: '数学比历史难多了',
    pinyin: 'Shùxué bǐ lìshǐ nánduō le',
    en: 'Maths is much harder than history',
    focus: '比较句2：A比B + Adj + 一点儿/一些/得多/多了 · 概数的表达1',
    texts: [
      {
        title: 'Text 1 · 在教室  In the classroom',
        lines: [
          { s: 'A', c: '大山，你和马可谁个子高？', p: 'Dàshān, nǐ hé Mǎkè shéi gèzi gāo?', en: 'Dashan, who is taller, you or Marco?' },
          { s: 'B', c: '马可比我高，我比马可矮一点儿。', p: 'Mǎkè bǐ wǒ gāo, wǒ bǐ Mǎkè ǎi yìdiǎnr.', en: 'Marco is taller than me; I am a little shorter than Marco.' },
          { s: 'A', c: '那你们谁大？', p: 'Nà nǐmen shéi dà?', en: 'Then which of you is older?' },
          { s: 'B', c: '我比马可大两岁。', p: 'Wǒ bǐ Mǎkè dà liǎng suì.', en: 'I am two years older than Marco.' },
          { s: 'A', c: '你们谁的汉语说得更好？', p: 'Nǐmen shéi de Hànyǔ shuō de gèng hǎo?', en: 'Which of you speaks Chinese better?' },
          { s: 'B', c: '马可比我说得好一些，我的汉语没有他好。', p: 'Mǎkè bǐ wǒ shuō de hǎo yìxiē, wǒ de Hànyǔ méiyǒu tā hǎo.', en: 'Marco speaks a little better than I do; my Chinese is not as good as his.' },
        ],
      },
      {
        title: 'Text 2 · 在教室  In the classroom',
        lines: [
          { s: 'A', c: '我喜欢历史课、体育课，不喜欢数学课。', p: 'Wǒ xǐhuan lìshǐ kè, tǐyù kè, bù xǐhuan shùxué kè.', en: "I like history and P.E., but I don't like maths." },
          { s: 'B', c: '为什么？数学也很有意思啊。', p: 'Wèi shénme? Shùxué yě hěn yǒu yìsi a.', en: 'Why? Maths is also very interesting.' },
          { s: 'A', c: '我觉得数学比历史难多了，我听不懂。', p: 'Wǒ juéde shùxué bǐ lìshǐ nán duō le, wǒ tīng bu dǒng.', en: 'I think maths is much harder than history. I cannot understand it.' },
          { s: 'B', c: '别担心，我可以帮你。', p: 'Bié dān xīn, wǒ kěyǐ bāng nǐ.', en: 'Do not worry; I can help you.' },
          { s: 'A', c: '好啊，我们每天学多长时间？', p: 'Hǎo a, wǒmen měi tiān xué duō cháng shíjiān?', en: 'Okay. How long should we study each day?' },
          { s: 'B', c: '一两个小时吧。', p: 'Yì-liǎng ge xiǎoshí ba.', en: 'One or two hours.' },
        ],
      },
      {
        title: 'Text 3 · 在休息室  In the lounge',
        lines: [
          { s: 'A', c: '你最近比以前来得早多了，搬家了？', p: 'Nǐ zuìjìn bǐ yǐqián lái de zǎo duō le, bān jiā le?', en: 'You have been arriving much earlier than before. Did you move?' },
          { s: 'B', c: '是啊，你不知道？我上个月就搬家了，走路二十分钟就到。', p: 'Shì a, nǐ bù zhīdào? Wǒ shàng ge yuè jiù bān jiā le, zǒu lù èrshí fēnzhōng jiù dào.', en: "Yes. Didn't you know? I moved last month; it takes only twenty minutes to walk here." },
          { s: 'A', c: '那很方便啊。', p: 'Nà hěn fāngbiàn a.', en: "That's very convenient." },
          { s: 'B', c: '我还打算买辆自行车，骑车七八分钟就能到。', p: 'Wǒ hái dǎsuan mǎi liàng zìxíngchē, qí chē qī-bā fēnzhōng jiù néng dào.', en: 'I am also planning to buy a bicycle; it would take only seven or eight minutes by bike.' },
          { s: 'A', c: '你不是有一辆吗？', p: 'Nǐ bú shì yǒu yí liàng ma?', en: "Don't you already have one?" },
          { s: 'B', c: '那辆太旧了，要换一辆，很便宜，两三百块钱。', p: 'Nà liàng tài jiù le, yào huàn yí liàng, hěn piányi, liǎng-sān bǎi kuài qián.', en: 'That one is too old, so I want to replace it. A new one is very cheap, only two or three hundred yuan.' },
        ],
      },
      {
        title: 'Text 4 · 在看房子  Seeing an apartment',
        lines: [
          { s: 'A', c: '这两个地方的房子一样吗？', p: 'Zhè liǎng ge dìfang de fángzi yíyàng ma?', en: 'Are the homes in these two places the same?' },
          { s: 'B', c: '不一样。您看，学校外边的房子比学校里边的大一些。', p: 'Bù yíyàng. Nín kàn, xuéxiào wàibian de fángzi bǐ xuéxiào lǐbian de dà yìxiē.', en: 'No. Look, the homes outside the school are a little larger than those inside it.' },
          { s: 'A', c: '大小没关系，主要是环境，哪个更安静？', p: 'Dàxiǎo méi guānxi, zhǔyào shì huánjìng, nǎge gèng ānjìng?', en: 'Size does not matter; the main thing is the environment. Which is quieter?' },
          { s: 'B', c: '学校里边的没有学校外边的那么安静。', p: 'Xuéxiào lǐbian de méiyǒu xuéxiào wàibian de nàme ānjìng.', en: 'The ones inside the school are not as quiet as those outside it.' },
          { s: 'A', c: '哪个方便一些呢？', p: 'Nǎge fāngbiàn yìxiē ne?', en: 'Which is a little more convenient?' },
          { s: 'B', c: '学校里边比学校外边方便，附近有三四个车站。', p: 'Xuéxiào lǐbian bǐ xuéxiào wàibian fāngbiàn, fùjìn yǒu sān-sì ge chēzhàn.', en: 'Inside the school is more convenient; there are three or four bus stops nearby.' },
        ],
      },
    ],
    vocab: [
      { c: '个子', p: 'gèzi', pos: 'n.', en: 'height, stature' },
      { c: '矮', p: 'ǎi', pos: 'adj.', en: 'short' },
      { c: '历史', p: 'lìshǐ', pos: 'n.', en: 'history' },
      { c: '体育', p: 'tǐyù', pos: 'n.', en: 'P.E., sports' },
      { c: '数学', p: 'shùxué', pos: 'n.', en: 'maths' },
      { c: '方便', p: 'fāngbiàn', pos: 'adj.', en: 'convenient' },
      { c: '自行车', p: 'zìxíngchē', pos: 'n.', en: 'bicycle' },
      { c: '骑', p: 'qí', pos: 'v.', en: 'to ride' },
      { c: '旧', p: 'jiù', pos: 'adj.', en: 'old, used, worn' },
      { c: '换', p: 'huàn', pos: 'v.', en: 'to change, to substitute' },
      { c: '地方', p: 'dìfang', pos: 'n.', en: 'place' },
      { c: '中介', p: 'zhōngjiè', pos: 'n.', en: 'intermediary, agent', supplementary: true },
      { c: '主要', p: 'zhǔyào', pos: 'adj.', en: 'main' },
      { c: '环境', p: 'huánjìng', pos: 'n.', en: 'environment' },
      { c: '附近', p: 'fùjìn', pos: 'n.', en: 'nearby, vicinity' },
    ],
    notes: [
      {
        title: '比较句2：A比B+Adj+一点儿/一些/得多/多了 · Comparative Sentences 2: A比B + Adj + 一点儿/一些/得多/多了',
        summary: '一点儿 and 一些 after the adjective indicate a slight difference in an A比B comparison; 得多 and 多了 indicate a large difference. The negative form is “A 没有 B (+ 这么/那么) + Adj”.',
        examples: [
          { c: '大山比大卫矮一点儿。', p: 'Dàshān bǐ Dàwèi ǎi yìdiǎnr.', en: 'Dashan is a little shorter than David.' },
          { c: '我今天起得比昨天晚一些。', p: 'Wǒ jīntiān qǐ de bǐ zuótiān wǎn yìxiē.', en: 'I got up a little later today than yesterday.' },
          { c: '今天的作业比昨天多得多。', p: 'Jīntiān de zuòyè bǐ zuótiān duō de duō.', en: "Today's homework is much greater in amount than yesterday's." },
          { c: '数学比历史难多了。', p: 'Shùxué bǐ lìshǐ nán duō le.', en: 'Maths is much harder than history.' },
          { c: '咖啡没有茶好喝。', p: 'Kāfēi méiyǒu chá hǎohē.', en: 'Coffee is not as tasty as tea.' },
          { c: '他没有我这么高。', p: 'Tā méiyǒu wǒ zhème gāo.', en: 'He is not as tall as I am.' },
          { c: '这个电影没有那个电影那么有意思。', p: 'Zhège diànyǐng méiyǒu nàge diànyǐng nàme yǒu yìsi.', en: 'This film is not as interesting as that one.' },
          { c: '学校里边的（房子）没有学校外边的那么安静。', p: 'Xuéxiào lǐbian de (fángzi) méiyǒu xuéxiào wàibian de nàme ānjìng.', en: 'The homes inside the school are not as quiet as those outside it.' },
        ],
      },
      {
        title: '概数的表达1 · Expression of Approximate Numbers 1',
        summary: 'Two adjacent numerals may be used together to express an approximate number, such as 一二（两）, 两三, 三四, 五六, 七八, and 八九.',
        examples: [
          { c: '我每天学习一两个小时汉语。', p: 'Wǒ měi tiān xuéxí yì-liǎng ge xiǎoshí Hànyǔ.', en: 'I study Chinese for one or two hours every day.' },
          { c: '你都喝了三四杯咖啡了，别再喝了！', p: 'Nǐ dōu hē le sān-sì bēi kāfēi le, bié zài hē le!', en: 'You have already had three or four cups of coffee; do not drink any more!' },
          { c: '从小丽家到公司骑车七八分钟就能到。', p: 'Cóng Xiǎolì jiā dào gōngsī qí chē qī-bā fēnzhōng jiù néng dào.', en: "It takes only seven or eight minutes to cycle from Xiaoli's home to the office." },
          { c: '学校里边比学校外边方便，附近有三四个车站。', p: 'Xuéxiào lǐbian bǐ xuéxiào wàibian fāngbiàn, fùjìn yǒu sān-sì ge chēzhàn.', en: 'Inside the school is more convenient; there are three or four bus stops nearby.' },
        ],
      },
    ],
  },
]
